import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { applyBookkeepingBatch, approveBookkeepingBatchPlan, createBookkeepingBatchRun, planBookkeepingBatch } from "../../core/bookkeeping-batch";
import { envelopeShape, wrapCoreResult } from "../envelope";
import { confirmField, withCompanyDb, withCompanyDbConfirmed } from "../tool-runtime";
import { currentMcpAuthenticatedPrincipal } from "../security";
const dates = { companyId: z.number().int().positive(), accountingFrom: z.string(), accountingTo: z.string(), bankFrom: z.string(), bankTo: z.string() };
export function registerBookkeepingBatchTools(server: McpServer): void {
 const principal=()=>{const value=currentMcpAuthenticatedPrincipal();return value?{kind:value.kind,subjectId:value.subjectId}:undefined};
 const state=(db:any,runId:number)=>({run:db.query("SELECT id AS runId,run_key AS runKey,plan_hash AS planHash,plan_json AS plan,created_at AS createdAt FROM bookkeeping_batch_runs WHERE id=?").get(runId),events:db.query("SELECT event_type AS type,plan_hash AS planHash,actor,detail_json AS detail,created_at AS createdAt FROM bookkeeping_batch_events WHERE run_id=? ORDER BY id").all(runId),attempts:db.query("SELECT action_key AS actionKey,outcome,error_text AS error,created_at AS createdAt FROM bookkeeping_batch_item_attempts WHERE run_id=? ORDER BY id").all(runId),receipts:db.query("SELECT action_key AS actionKey,receipt_json AS receipt,created_at AS createdAt FROM bookkeeping_batch_item_receipts WHERE run_id=? ORDER BY id").all(runId),checks:db.query("SELECT check_name AS name,ok,detail_json AS detail,created_at AS createdAt FROM bookkeeping_batch_final_checks WHERE run_id=? ORDER BY id").all(runId)});
 server.registerTool("bookkeeping_batch_dry_run", { title: "Persist bookkeeping batch plan", description: "Persists a canonical immutable dry-run revision for review. Requires actor attribution and confirm:true.", inputSchema: { company:z.string().min(1),runKey:z.string().min(1),...dates,confirm:confirmField }, outputSchema: envelopeShape, annotations: { readOnlyHint:false, destructiveHint:false, idempotentHint:true, openWorldHint:false } }, withCompanyDbConfirmed<any>(server,"bookkeeping_batch_dry_run",({db,actor,args}) => { const plan=planBookkeepingBatch(db,args); const run=createBookkeepingBatchRun(db,{...plan,runKey:args.runKey,actor:actor.createdBy,principal:principal()}); return wrapCoreResult({ok:true,dryRun:true,runId:run.runId,duplicate:run.duplicate,plan:run.plan,state:state(db,run.runId)}); }));
 server.registerTool("bookkeeping_batch_approve", { title:"Approve bookkeeping batch",description:"Approve exactly one reviewed plan hash. A stable principal may not approve its own plan.",inputSchema:{company:z.string().min(1),runId:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"bookkeeping_batch_approve",({db,actor,args})=>wrapCoreResult({...approveBookkeepingBatchPlan(db,{runId:args.runId,planHash:args.planHash,actor:actor.createdBy,principal:principal()}),state:state(db,args.runId)})));
 server.registerTool("bookkeeping_batch_apply", { title: "Apply bookkeeping batch", description: "Applies or resumes only the exact approved run and reviewed plan hash; it never replans or approves.", inputSchema: { company:z.string().min(1),runId:z.number().int().positive(),planHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField }, outputSchema: envelopeShape, annotations: { readOnlyHint:false, destructiveHint:false, idempotentHint:true, openWorldHint:false } }, withCompanyDbConfirmed<any>(server,"bookkeeping_batch_apply",({db,actor,args}) => wrapCoreResult({ ...applyBookkeepingBatch(db,{runId:args.runId,planHash:args.planHash,actor:actor.createdBy,principal:principal()}),runId:args.runId,planHash:args.planHash,state:state(db,args.runId) })));
 server.registerTool("bookkeeping_batch_status", { title:"Read bookkeeping batch evidence",description:"Read parsed run, events, attempts, receipts and final checks.",inputSchema:{company:z.string().min(1),runId:z.number().int().positive()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyDb<any>(server,({db,args})=>wrapCoreResult({ok:true,state:state(db,args.runId)})));
}
