import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { applyDimensionAssignment, changeDimensionDefinition, changeDimensionMember, createDimensionDefinition, createDimensionMember, listDimensionAssignments, listDimensionDefinitions, listDimensionMembers, planDimensionAssignment, supersedeDimensionAssignment } from "../../core/accounting-dimensions";
import { envelopeShape, successEnvelope, wrapCoreResult } from "../envelope";
import { confirmField, idempotencyKeyField, withCompanyDbConfirmed, withCompanyReadOnlyDb } from "../tool-runtime";
const allocations=z.array(z.object({dimensionId:z.string().min(1),memberId:z.string().min(1),amountMinor:z.number().int().positive(),currency:z.string().length(3)})).min(1);
const principal=(actor:any)=>actor.createdBy;
export function registerDimensionTools(server:McpServer){
 server.registerTool("dimension_assignment_plan",{title:"Plan journal dimensions",description:"Read-only, hash-bound classification proposal for an immutable journal line.",inputSchema:{company:z.string().min(1),journalLineId:z.number().int().positive(),allocations,source:z.enum(["reviewed","imported"]).optional(),reviewedImport:z.boolean().optional()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>successEnvelope(planDimensionAssignment(db,args))));
 server.registerTool("dimension_assignment_list",{title:"Inspect journal dimensions",description:"Read-only append-only dimension assignment history.",inputSchema:{company:z.string().min(1),journalLineId:z.number().int().positive()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>successEnvelope({assignments:listDimensionAssignments(db,args.journalLineId)})));
 server.registerTool("dimension_definition_list",{title:"Inspect dimension definitions",description:"Read append-only definition history, including historical labels.",inputSchema:{company:z.string().min(1)},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db})=>successEnvelope({definitions:listDimensionDefinitions(db)})));
 server.registerTool("dimension_member_list",{title:"Inspect dimension members",description:"Read append-only member history, including historical labels.",inputSchema:{company:z.string().min(1),dimensionId:z.string().min(1).optional()},outputSchema:envelopeShape,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},withCompanyReadOnlyDb<any>(({db,args})=>successEnvelope({members:listDimensionMembers(db,args.dimensionId)})));
 server.registerTool("dimension_definition_create",{title:"Create dimension definition",description:"Create a company-scoped append-only dimension definition.",inputSchema:{company:z.string().min(1),dimensionId:z.string().min(1),kind:z.string().min(1),name:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_definition_create",({db,actor,args})=>wrapCoreResult(createDimensionDefinition(db,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
 server.registerTool("dimension_member_create",{title:"Create dimension member",description:"Create a company-scoped append-only dimension member.",inputSchema:{company:z.string().min(1),dimensionId:z.string().min(1),memberId:z.string().min(1),name:z.string().min(1),status:z.enum(["active","inactive"]).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_member_create",({db,actor,args})=>wrapCoreResult(createDimensionMember(db,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
 const lifecycle=z.enum(["activate","deactivate","rename","supersede"]);
 server.registerTool("dimension_definition_lifecycle",{title:"Change dimension lifecycle",description:"Append an activate, deactivate, rename or supersede event; stable identity and historical labels remain queryable.",inputSchema:{company:z.string().min(1),dimensionId:z.string().min(1),action:lifecycle,name:z.string().min(1).optional(),supersedesId:z.string().min(1).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_definition_lifecycle",({db,actor,args})=>wrapCoreResult(changeDimensionDefinition(db,args.action,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
 server.registerTool("dimension_member_lifecycle",{title:"Change dimension member lifecycle",description:"Append an activate, deactivate, rename or supersede event; stable identity and historical labels remain queryable.",inputSchema:{company:z.string().min(1),dimensionId:z.string().min(1),memberId:z.string().min(1),action:lifecycle,name:z.string().min(1).optional(),supersedesId:z.string().min(1).optional(),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_member_lifecycle",({db,actor,args})=>wrapCoreResult(changeDimensionMember(db,args.action,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
 server.registerTool("dimension_assignment_apply",{title:"Apply journal dimensions",description:"Append the exact reviewed dimensions; journal bytes and legal totals remain unchanged.",inputSchema:{company:z.string().min(1),journalLineId:z.number().int().positive(),allocations,source:z.enum(["reviewed","imported"]).optional(),reviewedImport:z.boolean().optional(),planHash:z.string().length(64),idempotencyKey:idempotencyKeyField,confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_assignment_apply",({db,actor,args})=>wrapCoreResult(applyDimensionAssignment(db,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
 server.registerTool("dimension_assignment_supersede",{title:"Supersede journal dimensions",description:"Append a documented correction without rewriting journal evidence.",inputSchema:{company:z.string().min(1),assignmentId:z.number().int().positive(),reason:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},withCompanyDbConfirmed<any>(server,"dimension_assignment_supersede",({db,actor,args})=>wrapCoreResult(supersedeDimensionAssignment(db,{...args,actor:actor.createdBy,principal:principal(actor),confirm:true}))));
}
