/** Thin MCP parity for the workspace-only #578 lifecycle.  The security
 * layer authorizes both legal-company endpoints before these handlers run. */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { resolveConfiguredWorkspaceRoot } from "../../core/workspace";
import { openWorkspaceControlDb, openWorkspaceControlReadOnlyDb } from "../../core/workspace-control";
import { approveIntercompanyDisposition, inspectIntercompanyDisposition, intercompanyDispositionStatus, linkIntercompanyDispositionJournal, planIntercompanyDisposition, proposeIntercompanyDisposition, reopenIntercompanyDisposition, settleIntercompanyDisposition, supersedeIntercompanyDisposition } from "../../core/intercompany-dispositions";
import { envelopeShape, errorEnvelope, successEnvelope } from "../envelope";
import { confirmField, withCompanyDb, withCompanyDbConfirmed } from "../tool-runtime";
import { currentMcpAuthenticatedPrincipal } from "../security";
import { authorizeWorkspaceRoute } from "../../core/workspace-access";

const company=z.string().min(1), hash=z.string().regex(/^[a-f0-9]{64}$/), side=z.enum(["left","right"]);
const read={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false} as const;
const write={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false} as const;
const workspace=()=>resolveConfiguredWorkspaceRoot()??(()=>{throw new Error("RENTEMESTER_WORKSPACE is required for intercompany dispositions");})();
const principal=()=>{const value=currentMcpAuthenticatedPrincipal();return value?{kind:"service" as const,id:value.subjectId}:{kind:"user" as const,id:"local-operator"};};
function assertEndpoints(db:any, value:any){const auth=currentMcpAuthenticatedPrincipal();if(!auth) return;const endpoints=[value?.left?.companySlug,value?.right?.companySlug];if(endpoints.length!==2||endpoints.some((slug)=>typeof slug!=="string")||endpoints[0]===endpoints[1])throw new Error("disposition requires two distinct legal-company endpoints");for(const slug of endpoints)if(!authorizeWorkspaceRoute(db,workspace(),{userId:auth.subjectId,companySlug:slug,permission:"company.ownership.manage"}).allowed)throw new Error("disposition not found");}

export function registerIntercompanyDispositionTools(server:McpServer):void {
  server.registerTool("intercompany_disposition_plan",{title:"Dry-run intercompany disposition",description:"Validates both legal sides and source evidence. It has no workspace or ledger effects.",inputSchema:{company,disposition:z.unknown()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{return successEnvelope(planIntercompanyDisposition(db,args.disposition));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_propose",{title:"Propose two-sided intercompany disposition",description:"Records immutable source-linked evidence only. Each legal company must still post through its normal flow.",inputSchema:{company,disposition:z.unknown(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_propose",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(proposeIntercompanyDisposition(db,args.disposition,{actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_approve",{title:"Approve exact intercompany disposition",description:"Approves an exact proposal with a distinct stable principal; it never posts either ledger.",inputSchema:{company,dispositionId:z.string().min(3),payloadHash:hash,confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_approve",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(approveIntercompanyDisposition(db,args.dispositionId,args.payloadHash,{actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_link",{title:"Link independently posted journal",description:"Validates the current posted journal, source currency/date/side and ledger head, then records one immutable link. It never posts a ledger entry.",inputSchema:{company,dispositionId:z.string().min(3),payloadHash:hash,side,journalEntryId:z.number().int().positive(),ledgerHeadHash:hash.nullable(),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_link",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(linkIntercompanyDispositionJournal(db,workspace(),{dispositionId:args.dispositionId,payloadHash:args.payloadHash,side:args.side,journalEntryId:args.journalEntryId,expectedLedgerHeadHash:args.ledgerHeadHash,actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_status",{title:"Inspect intercompany disposition status",description:"Read-only current status with one-sided, stale/reversed and overdue exceptions. Hidden endpoints are denied before this tool runs.",inputSchema:{company,dispositionId:z.string().min(3),asOf:z.string().optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>{const db=openWorkspaceControlReadOnlyDb(workspace());try{const result=intercompanyDispositionStatus(db,workspace(),args.dispositionId,args.asOf);return result?successEnvelope(result):errorEnvelope("disposition not found",{code:"INTERCOMPANY_DISPOSITION_NOT_FOUND"});}finally{db.close();}}));
  server.registerTool("intercompany_disposition_settle",{title:"Settle fully posted intercompany disposition",description:"Appends settlement evidence only after both current legal-ledger links validate; it never posts either ledger.",inputSchema:{company,dispositionId:z.string().min(3),payloadHash:hash,settlementEvidenceRecordIds:z.array(z.string().min(3)).min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_settle",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(settleIntercompanyDisposition(db,workspace(),{...args,actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_reopen",{title:"Reopen settled or superseded intercompany disposition",description:"Appends a reopen decision only after current journal and ledger-head validation; it never changes a ledger.",inputSchema:{company,dispositionId:z.string().min(3),payloadHash:hash,reason:z.string().min(1).max(1000),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_reopen",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{return successEnvelope(reopenIntercompanyDisposition(db,workspace(),{...args,actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
  server.registerTool("intercompany_disposition_supersede",{title:"Supersede active intercompany disposition",description:"Appends a replacement reference to an existing disposition; it never deletes evidence or writes a ledger.",inputSchema:{company,dispositionId:z.string().min(3),payloadHash:hash,replacementDispositionId:z.string().min(3),reason:z.string().min(1).max(1000),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"intercompany_disposition_supersede",({args,actor})=>{const db=openWorkspaceControlDb(workspace());try{const original=inspectIntercompanyDisposition(db,args.dispositionId),replacement=inspectIntercompanyDisposition(db,args.replacementDispositionId);if(!original||!replacement)return errorEnvelope("disposition not found",{code:"INTERCOMPANY_DISPOSITION_NOT_FOUND"});assertEndpoints(db,original.disposition);assertEndpoints(db,replacement.disposition);return successEnvelope(supersedeIntercompanyDisposition(db,{...args,actor:actor.createdBy,principal:principal()}));}finally{db.close();}}));
}
