import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { applySupplierCommitment, changeSupplierCommitment, listSupplierCommitments, listSupplierCommitmentOccurrenceMatches, matchSupplierCommitmentOccurrence, planSupplierCommitment, supplierCommitmentAlerts } from "../../core/supplier-commitments";
import { envelopeShape, wrapCoreResult } from "../envelope";
import { confirmField, idempotencyKeyField, withCompanyDb, withCompanyDbConfirmed } from "../tool-runtime";
const commitment=z.object({commitmentId:z.string().min(3),vendorPartyId:z.string().min(3),vendorSnapshot:z.string().optional(),type:z.string().min(1),description:z.string().min(1),businessPurpose:z.string().min(1),amount:z.number().positive(),currency:z.string().regex(/^[A-Z]{3}$/),frequency:z.enum(["weekly","monthly","quarterly","yearly"]),nextDate:z.string().min(10),startDate:z.string().optional(),renewalDate:z.string().optional(),noticeDate:z.string().optional(),endDate:z.string().optional(),evidenceRefs:z.array(z.string().min(1)).min(1),vatProposal:z.string().optional(),status:z.enum(["active","paused","ended","unresolved"]).optional()});
export function registerSupplierCommitmentTools(server:McpServer):void {
 const read={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false} as const,write={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false} as const;
 server.registerTool("supplier_commitment_plan",{title:"Plan supplier commitment",description:"Strict read-only proposal from reviewed source references. Name/amount similarity never creates a vendor or contract.",inputSchema:{company:z.string().min(1),commitment},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({args})=>wrapCoreResult(planSupplierCommitment(args.commitment))));
 server.registerTool("supplier_commitment_apply",{title:"Approve supplier commitment",description:"Stores immutable planning evidence only; it never creates a payable, journal, payment or supplier message. Requires confirm and authenticated principal.",inputSchema:{company:z.string().min(1),commitment,payloadHash:z.string().regex(/^[a-f0-9]{64}$/),confirm:confirmField,idempotencyKey:idempotencyKeyField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"supplier_commitment_apply",({db,args,actor})=>wrapCoreResult(applySupplierCommitment(db,{...args.commitment,payloadHash:args.payloadHash,confirm:args.confirm===true,actor:actor.createdBy,principal:actor.createdBy,idempotencyKey:args.idempotencyKey}))));
 server.registerTool("supplier_commitment_list",{title:"List active supplier commitments",description:"Read-only current approved commitment records and source hashes.",inputSchema:{company:z.string().min(1)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({db})=>wrapCoreResult({ok:true,rows:listSupplierCommitments(db),errors:[]})));
 server.registerTool("supplier_commitment_change",{title:"Pause, end or supersede commitment",description:"Appends lifecycle evidence; historical occurrences and forecasts remain intact. Requires confirm and authenticated principal.",inputSchema:{company:z.string().min(1),commitmentId:z.string().min(3),action:z.enum(["paused","ended","superseded"]),reason:z.string().min(1),confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"supplier_commitment_change",({db,args,actor})=>wrapCoreResult(changeSupplierCommitment(db,{...args,confirm:args.confirm===true,actor:actor.createdBy,principal:actor.createdBy}))));
 const evidence=z.object({kind:z.enum(["canonical_document","payable","bank_transaction"]),id:z.string().min(1),date:z.string().min(10),amount:z.number().nonnegative(),currency:z.string().regex(/^[A-Z]{3}$/),partyId:z.string().min(1).optional(),documented:z.boolean().optional()});
 server.registerTool("supplier_commitment_match",{title:"Confirm commitment occurrence evidence",description:"Append-only confirmed link from an expected occurrence to canonical document, payable, or bank evidence. FX is never inferred.",inputSchema:{company:z.string().min(1),commitmentId:z.string().min(3),occurrenceDate:z.string().min(10),evidence,confirm:confirmField},outputSchema:envelopeShape,annotations:write},withCompanyDbConfirmed<any>(server,"supplier_commitment_match",({db,args,actor})=>wrapCoreResult(matchSupplierCommitmentOccurrence(db,{...args,confirm:args.confirm===true,actor:actor.createdBy,principal:actor.createdBy}))));
 server.registerTool("supplier_commitment_matches",{title:"List commitment occurrence matches",description:"Read append-only evidence links and deterministic variances.",inputSchema:{company:z.string().min(1),commitmentId:z.string().min(3).optional()},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({db,args})=>wrapCoreResult({ok:true,rows:listSupplierCommitmentOccurrenceMatches(db,args.commitmentId),errors:[]})));
 server.registerTool("supplier_commitment_alerts",{title:"List renewal and notice alerts",description:"Read upcoming renewal and notice dates from approved commitments.",inputSchema:{company:z.string().min(1),asOf:z.string().min(10)},outputSchema:envelopeShape,annotations:read},withCompanyDb<any>(server,({db,args})=>wrapCoreResult({ok:true,rows:supplierCommitmentAlerts(db,args.asOf),errors:[]})));
}
