import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { okResponse } from "./_shared";
import { companyRootForSlug } from "../../core/workspace";
import { companyPaths } from "../../core/paths";
import { migrate, openDb } from "../../core/db";
import { applyBookkeepingBatch, approveBookkeepingBatchPlan, createBookkeepingBatchRun, planBookkeepingBatch } from "../../core/bookkeeping-batch";
function scope(body: Record<string, unknown>) { const get=(k:string)=>body[k]; if (!Number.isInteger(get("companyId")) || !["accountingFrom","accountingTo","bankFrom","bankTo"].every(k=>typeof get(k)==="string")) throw ApiError.badRequest("companyId and four ISO date bounds are required"); return { companyId:get("companyId") as number, accountingFrom:get("accountingFrom") as string, accountingTo:get("accountingTo") as string, bankFrom:get("bankFrom") as string, bankTo:get("bankTo") as string }; }
export function handleBookkeepingBatchDryRun(config:ServerConfig, slug:string, url:URL):Response { const s=scope({companyId:Number(url.searchParams.get("companyId")),accountingFrom:url.searchParams.get("accountingFrom"),accountingTo:url.searchParams.get("accountingTo"),bankFrom:url.searchParams.get("bankFrom"),bankTo:url.searchParams.get("bankTo")}); const db=openDb(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db); try { migrate(db); return okResponse({dryRun:true,plan:planBookkeepingBatch(db,s)}); } finally { db.close(); } }
function state(db:any,runId:number){return {run:db.query("SELECT id AS runId,run_key AS runKey,plan_hash AS planHash,plan_json AS plan,created_at AS createdAt FROM bookkeeping_batch_runs WHERE id=?").get(runId),events:db.query("SELECT event_type AS type,plan_hash AS planHash,actor,detail_json AS detail,created_at AS createdAt FROM bookkeeping_batch_events WHERE run_id=? ORDER BY id").all(runId),attempts:db.query("SELECT action_key AS actionKey,outcome,error_text AS error,created_at AS createdAt FROM bookkeeping_batch_item_attempts WHERE run_id=? ORDER BY id").all(runId),receipts:db.query("SELECT action_key AS actionKey,receipt_json AS receipt,created_at AS createdAt FROM bookkeeping_batch_item_receipts WHERE run_id=? ORDER BY id").all(runId),checks:db.query("SELECT check_name AS name,ok,detail_json AS detail,created_at AS createdAt FROM bookkeeping_batch_final_checks WHERE run_id=? ORDER BY id").all(runId)}}
function runId(body:Record<string,unknown>){if(!Number.isInteger(body.runId)||Number(body.runId)<=0)throw ApiError.badRequest("runId is required");return Number(body.runId)}
function planHash(body:Record<string,unknown>){if(typeof body.planHash!=="string"||!/^[a-f0-9]{64}$/.test(body.planHash))throw ApiError.badRequest("planHash is required");return body.planHash}
export async function handleBookkeepingBatchPersistDryRun(config:ServerConfig,request:Request,slug:string):Promise<Response>{const result=await withCompanyMutation(request,config,slug,({db,actor},body)=>{if(typeof body.runKey!=="string"||!body.runKey)throw ApiError.badRequest("runKey is required");const plan=planBookkeepingBatch(db,scope(body));const run=createBookkeepingBatchRun(db,{...plan,runKey:body.runKey,actor:actor.createdBy});return {ok:true,dryRun:true,runId:run.runId,duplicate:run.duplicate,plan:run.plan,state:state(db,run.runId)}},{requireConfirm:true});return okResponse(result)}
export async function handleBookkeepingBatchApprove(config:ServerConfig,request:Request,slug:string):Promise<Response>{return okResponse(await withCompanyMutation(request,config,slug,({db,actor},body)=>({...approveBookkeepingBatchPlan(db,{runId:runId(body),planHash:planHash(body),actor:actor.createdBy}),state:state(db,runId(body))}),{requireConfirm:true}))}
export async function handleBookkeepingBatchApply(config:ServerConfig, request:Request, slug:string):Promise<Response> { return okResponse(await withCompanyMutation(request,config,slug,({db,actor},body)=>({...applyBookkeepingBatch(db,{runId:runId(body),planHash:planHash(body),actor:actor.createdBy}),runId:runId(body),planHash:planHash(body),state:state(db,runId(body))}),{requireConfirm:true})); }
export function handleBookkeepingBatchStatus(config:ServerConfig,slug:string,run:number):Response{const db=openDb(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{migrate(db);return okResponse({state:state(db,run)})}finally{db.close()}}
