import { openLedgerReadOnly } from "../../core/ledger-inspection";
import { companyPaths } from "../../core/paths";
import { companyRootForSlug } from "../../core/workspace";
import { applyDimensionAssignment, changeDimensionDefinition, changeDimensionMember, createDimensionDefinition, createDimensionMember, listDimensionAssignments, listDimensionDefinitions, listDimensionMembers, planDimensionAssignment, replaceDimensionAssignment, supersedeDimensionAssignment } from "../../core/accounting-dimensions";
import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { okResponse, readJsonBody } from "./_shared";
const principal=(config:ServerConfig)=>config.requestPrincipal?.serviceAccountId?`service-account:${config.requestPrincipal.serviceAccountId}`:config.requestPrincipal?.id??"";
const allocations=(body:Record<string,unknown>)=>Array.isArray(body.allocations)?body.allocations as any[]:[];
export function handleDimensionAssignments(config:ServerConfig,slug:string,lineId:number):Response { if(!Number.isInteger(lineId)||lineId<=0)throw ApiError.badRequest("journal line id is required");const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse({assignments:listDimensionAssignments(db,lineId)});}finally{db.close();} }
export function handleDimensionDefinitions(config:ServerConfig,slug:string):Response {const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse({definitions:listDimensionDefinitions(db)});}finally{db.close();} }
export function handleDimensionMembers(config:ServerConfig,slug:string,dimensionId?:string):Response {const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse({members:listDimensionMembers(db,dimensionId)});}finally{db.close();} }
export async function handleDimensionPlan(config:ServerConfig,slug:string,request:Request):Promise<Response>{const body=await readJsonBody(request);const db=openLedgerReadOnly(companyPaths(companyRootForSlug(config.workspaceRoot,slug)).db);try{return okResponse(planDimensionAssignment(db,{journalLineId:Number(body.journalLineId),allocations:allocations(body),source:body.source as any,reviewedImport:body.reviewedImport===true,sourceRef:typeof body.sourceRef==="string"?body.sourceRef:undefined}));}finally{db.close();}}
export async function handleDimensionAction(config:ServerConfig,slug:string,request:Request,action:"define"|"member"|"apply"|"replace"|"supersede"|"definition-lifecycle"|"member-lifecycle"):Promise<Response>{return okResponse(await withCompanyMutation(request,config,slug,(ctx,body)=>{const identity={actor:ctx.actor.createdBy,principal:principal(config),confirm:true};if(action==="define")return createDimensionDefinition(ctx.db,{...identity,dimensionId:String(body.dimensionId??""),kind:String(body.kind??""),name:String(body.name??"")});if(action==="member")return createDimensionMember(ctx.db,{...identity,dimensionId:String(body.dimensionId??""),memberId:String(body.memberId??""),name:String(body.name??""),status:body.status as any,effectiveFrom:typeof body.effectiveFrom==="string"?body.effectiveFrom:undefined,effectiveTo:typeof body.effectiveTo==="string"?body.effectiveTo:undefined});if(action==="definition-lifecycle")return changeDimensionDefinition(ctx.db,body.action as any,{...identity,dimensionId:String(body.dimensionId??""),name:typeof body.name==="string"?body.name:undefined,supersedesId:typeof body.supersedesId==="string"?body.supersedesId:undefined});if(action==="member-lifecycle")return changeDimensionMember(ctx.db,body.action as any,{...identity,dimensionId:String(body.dimensionId??""),memberId:String(body.memberId??""),name:typeof body.name==="string"?body.name:undefined,supersedesId:typeof body.supersedesId==="string"?body.supersedesId:undefined});if(action==="apply")return applyDimensionAssignment(ctx.db,{...identity,journalLineId:Number(body.journalLineId),allocations:allocations(body),source:body.source as any,reviewedImport:body.reviewedImport===true,sourceRef:typeof body.sourceRef==="string"?body.sourceRef:undefined,planHash:String(body.planHash??""),idempotencyKey:typeof body.idempotencyKey==="string"?body.idempotencyKey:undefined});if(action==="replace")return replaceDimensionAssignment(ctx.db,{...identity,journalLineId:Number(body.journalLineId),allocations:allocations(body),source:body.source as any,reviewedImport:body.reviewedImport===true,sourceRef:typeof body.sourceRef==="string"?body.sourceRef:undefined,expectedAssignmentId:Number(body.expectedAssignmentId),reason:String(body.reason??""),planHash:String(body.planHash??""),idempotencyKey:typeof body.idempotencyKey==="string"?body.idempotencyKey:undefined});return supersedeDimensionAssignment(ctx.db,{...identity,assignmentId:Number(body.assignmentId),reason:String(body.reason??"")});},{requireConfirm:true}));}
