import type { ServerConfig } from "../config";
import { buildCompanyCommitments } from "../data/commitments-view";
import { applySupplierCommitment, changeSupplierCommitment, planSupplierCommitment } from "../../core/supplier-commitments";
import { withCompanyMutation } from "../mutations";
import { okResponse, requireString } from "./_shared";
import { ApiError } from "../errors";
export function handleSupplierCommitments(config:ServerConfig,slug:string,url:URL):Response { const startDate=url.searchParams.get("startDate")??new Date().toISOString().slice(0,10); return okResponse({supplierCommitments:buildCompanyCommitments(config.workspaceRoot,slug,startDate)}); }
export async function handleSupplierCommitmentPlan(config:ServerConfig,request:Request,slug:string):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(_ctx,body)=>{const commitment=body.commitment;if(!commitment||typeof commitment!=="object")throw ApiError.badRequest("commitment is required");return planSupplierCommitment(commitment as any);});return okResponse({plan:result});}
export async function handleSupplierCommitmentApply(config:ServerConfig,request:Request,slug:string):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const commitment=body.commitment;if(!commitment||typeof commitment!=="object")throw ApiError.badRequest("commitment is required");const payloadHash=requireString(body,"payloadHash");return applySupplierCommitment(ctx.db,{...(commitment as any),payloadHash,confirm:true,actor:ctx.actor.createdBy,principal:ctx.principal.id,idempotencyKey:typeof body.idempotencyKey==="string"?body.idempotencyKey:undefined});},{requireConfirm:true,keyIdempotent:"bookkeeping_batch_persist"});return okResponse({supplierCommitment:result});}
export async function handleSupplierCommitmentChange(config:ServerConfig,request:Request,slug:string):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const action=body.action;if(action!=="paused"&&action!=="ended"&&action!=="superseded")throw ApiError.badRequest("invalid action");return changeSupplierCommitment(ctx.db,{commitmentId:requireString(body,"commitmentId"),action,reason:requireString(body,"reason"),confirm:true,actor:ctx.actor.createdBy,principal:ctx.principal.id});},{requireConfirm:true});return okResponse({supplierCommitment:result});}
