/** Compact Cockpit HTTP adapter for #573/#575.  Company slug is the access
 * anchor; workspace records stay shared but are projected through the caller's
 * full live company membership set before pagination or inspection. */
import type { ServerConfig } from "../config";
import { ApiError } from "../errors";
import { withCompanyMutation } from "../mutations";
import { okResponse, readJsonBody, requireString } from "./_shared";
import { listWorkspaceCompanies } from "../../core/workspace";
import { authorizeWorkspaceRoute } from "../../core/workspace-access";
import { openWorkspaceControlDb, openWorkspaceControlReadOnlyDb } from "../../core/workspace-control";
import { approvePartyMerge, createParty, inspectParty, linkPartyRole, proposePartyMerge, searchParties } from "../../core/party-registry";
import { enrichCorporateRecord, ingestCorporateRecord, inspectCorporateRecord, linkCorporateRecord, listCorporateRecords, readCorporateRecordBytes, supersedeCorporateRecord } from "../../core/corporate-records";
import { companyKnowledgeHistory, proposeCompanyKnowledge, queryCompanyKnowledge, reviewCompanyKnowledge, supersedeCompanyKnowledge } from "../../core/company-knowledge";

function visibleCompanies(config:ServerConfig, permission:"company.read"|"company.master-data"|"company.review", anchor:string):Set<string> {
  const principal=config.requestPrincipal;
  if (!config.betterAuthProvider || !principal?.userId) return new Set([anchor]);
  const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot); try { return new Set(listWorkspaceCompanies(config.workspaceRoot).filter(c=>authorizeWorkspaceRoute(db,config.workspaceRoot,{userId:principal.userId!,companySlug:c.slug,permission}).allowed).map(c=>c.slug)); } finally {db.close();}
}
function partyVisible(config:ServerConfig,slug:string,id:string){const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return searchParties(db,{companySlugs:visibleCompanies(config,"company.read",slug),limit:100}).rows.find((p:any)=>p.partyId===id)??null;}finally{db.close();}}
function recordVisible(config:ServerConfig,slug:string,id:string){const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return listCorporateRecords(db,{companySlugs:visibleCompanies(config,"company.read",slug),limit:100}).rows.find((r:any)=>r.recordId===id)??null;}finally{db.close();}}
const positive=(raw:string|null, fallback:number)=>{const n=Number(raw??fallback);return Number.isSafeInteger(n)&&n>=0?n:fallback;};

export function handleRegistryParties(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(searchParties(db,{query:u.searchParams.get("query")??undefined,companySlugs:visibleCompanies(config,"company.read",slug),cursor:positive(u.searchParams.get("cursor"),0),limit:Math.min(100,Math.max(1,positive(u.searchParams.get("limit"),25)))}));}finally{db.close();}}
export function handleRegistryParty(config:ServerConfig,slug:string,id:string):Response {const party=partyVisible(config,slug,id);if(!party)throw ApiError.notFound("party not found");return okResponse({party});}
export async function handleRegistryPartyCreate(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const db=openWorkspaceControlDb(config.workspaceRoot);try{const role=requireString(body,"role");const party=createParty(db,{...body,actor:ctx.actor.createdBy}as any);return {ok:true,party:linkPartyRole(db,{partyId:(party as any).partyId,companySlug:slug,role:role as any,defaults:body.defaults as any,actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryPartyRole(config:ServerConfig,slug:string,id:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(!partyVisible(config,slug,id))throw ApiError.notFound("party not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{return {ok:true,party:linkPartyRole(db,{partyId:id,companySlug:slug,role:requireString(body,"role") as any,defaults:body.defaults as any,actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryPartyMerge(config:ServerConfig,slug:string,request:Request,approve:boolean):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const from= requireString(body,"fromPartyId");if(!partyVisible(config,slug,from))throw ApiError.notFound("party not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{if(approve)return {ok:true,party:approvePartyMerge(db,{fromPartyId:from,proposalHash:requireString(body,"proposalHash"),actor:ctx.actor.createdBy})};const into=requireString(body,"intoPartyId");if(!partyVisible(config,slug,into))throw ApiError.notFound("party not found");return {ok:true,proposalHash:proposePartyMerge(db,{fromPartyId:from,intoPartyId:into,reviewAssertion:requireString(body,"reviewAssertion"),actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}

export function handleRegistryRecords(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse(listCorporateRecords(db,{companySlugs:visibleCompanies(config,"company.read",slug),cursor:positive(u.searchParams.get("cursor"),0),limit:Math.min(100,Math.max(1,positive(u.searchParams.get("limit"),25)))}));}finally{db.close();}}
export function handleRegistryRecord(config:ServerConfig,slug:string,id:string):Response {const record=recordVisible(config,slug,id);if(!record)throw ApiError.notFound("corporate record not found");return okResponse({record});}
export function handleRegistryRecordDownload(config:ServerConfig,slug:string,id:string):Response {if(!recordVisible(config,slug,id))throw ApiError.notFound("corporate record not found");const db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse({bytesBase64:Buffer.from(readCorporateRecordBytes(db,id)).toString("base64"),sha256:inspectCorporateRecord(db,id)?.sha256});}finally{db.close();}}
export async function handleRegistryRecordIngest(config:ServerConfig,slug:string,request:Request):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(typeof body.bytesBase64!=="string")throw ApiError.badRequest("bytesBase64 is required");const db=openWorkspaceControlDb(config.workspaceRoot);try{const links=Array.isArray(body.links)?body.links:[];if(links.some((l:any)=>!l||typeof l!=="object"||l.type==="company"&&l.id!==slug))throw ApiError.badRequest("initial company link must be the authorized company");return {ok:true,record:ingestCorporateRecord(db,{...body,bytes:new Uint8Array(Buffer.from(body.bytesBase64,"base64")),links:[...links,{type:"company",id:slug}],actor:ctx.actor.createdBy}as any)};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
export async function handleRegistryRecordAction(config:ServerConfig,slug:string,id:string,request:Request,action:"link"|"enrich"|"supersede"):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{if(!recordVisible(config,slug,id))throw ApiError.notFound("corporate record not found");const db=openWorkspaceControlDb(config.workspaceRoot);try{if(action==="enrich")return {ok:true,payloadHash:enrichCorporateRecord(db,{recordId:id,assertion:requireString(body,"assertion"),actor:ctx.actor.createdBy})};if(action==="supersede")return {ok:true,payloadHash:supersedeCorporateRecord(db,{recordId:id,replacementRecordId:requireString(body,"replacementRecordId"),reason:requireString(body,"reason"),actor:ctx.actor.createdBy})};const type=requireString(body,"type");if(type==="company"&&requireString(body,"id")!==slug)throw ApiError.badRequest("company link must use the authorized company");return {ok:true,record:linkCorporateRecord(db,{recordId:id,type:type as any,id:requireString(body,"id"),actor:ctx.actor.createdBy})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}

const knowledgePrincipal=(principal:any)=>principal?.serviceAccountId?{kind:"service_account" as const,id:principal.serviceAccountId}:principal?.userId?{kind:"user" as const,id:principal.userId}:{kind:"local_operator" as const,id:"localhost"};
export function handleCompanyKnowledge(config:ServerConfig,slug:string,request:Request):Response {const u=new URL(request.url),db=openWorkspaceControlReadOnlyDb(config.workspaceRoot);try{return okResponse({context:queryCompanyKnowledge(db,{companySlug:slug,asOf:u.searchParams.get("asOf")??new Date().toISOString(),includeProposed:u.searchParams.get("includeProposed")==="true"}),history:companyKnowledgeHistory(db,slug)});}finally{db.close();}}
export async function handleCompanyKnowledgeAction(config:ServerConfig,slug:string,request:Request,action:"propose"|"review"|"supersede"):Promise<Response>{const result=await withCompanyMutation(request,config,slug,(ctx,body)=>{const db=openWorkspaceControlDb(config.workspaceRoot);try{const principal=knowledgePrincipal(ctx.principal);if(action==="propose")return {ok:true,assertion:proposeCompanyKnowledge(db,{...body,companySlug:slug,actor:ctx.actor.createdBy,principal}as any)};if(action==="review")return {ok:true,assertion:reviewCompanyKnowledge(db,{assertionId:requireString(body,"assertionId"),decision:requireString(body,"decision") as any,reason:typeof body.reason==="string"?body.reason:undefined,actor:ctx.actor.createdBy,principal})};return {ok:true,...supersedeCompanyKnowledge(db,{assertionId:requireString(body,"assertionId"),replacement:body.replacement as any,actor:ctx.actor.createdBy,principal})};}finally{db.close();}},{requireConfirm:true});return okResponse(result);}
