import type { CommandDispatch } from "../cli-dispatch";
import { openCommandDb } from "../cli-dispatch";
import { migrate } from "../core/db";
import { applyDimensionAssignment, changeDimensionDefinition, changeDimensionMember, createDimensionDefinition, createDimensionMember, listDimensionAssignments, listDimensionDefinitions, listDimensionMembers, planDimensionAssignment, replaceDimensionAssignment, supersedeDimensionAssignment } from "../core/accounting-dimensions";
import { applyDimensionBudget, listDimensionBudgets, planDimensionBudget } from "../core/budget";
const json=(v:string|undefined)=>{try{return v?JSON.parse(v):undefined;}catch{throw new Error("--allocations must be JSON");}};
export function register(dispatch:CommandDispatch) {
  const identity=(ctx:any)=>({actor:ctx.cliActor??ctx.inferredMutationActor()??undefined,principal:ctx.arg("--principal"),confirm:ctx.arg("--confirm")==="yes"});
  dispatch.on("dimensions","define",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(createDimensionDefinition(db,{...identity(ctx),dimensionId:ctx.arg("--dimension-id")!,kind:ctx.arg("--kind")!,name:ctx.arg("--name")!}));}finally{db.close();}});
  dispatch.on("dimensions","member",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(createDimensionMember(db,{...identity(ctx),dimensionId:ctx.arg("--dimension-id")!,memberId:ctx.arg("--member-id")!,name:ctx.arg("--name")!,status:ctx.arg("--status") as any,effectiveFrom:ctx.arg("--effective-from"),effectiveTo:ctx.arg("--effective-to")}));}finally{db.close();}});
  dispatch.on("dimensions","definition-lifecycle",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(changeDimensionDefinition(db,ctx.arg("--action") as any,{...identity(ctx),dimensionId:ctx.arg("--dimension-id")!,name:ctx.arg("--name"),supersedesId:ctx.arg("--supersedes-id")}));}finally{db.close();}});
  dispatch.on("dimensions","member-lifecycle",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(changeDimensionMember(db,ctx.arg("--action") as any,{...identity(ctx),dimensionId:ctx.arg("--dimension-id")!,memberId:ctx.arg("--member-id"),name:ctx.arg("--name"),supersedesId:ctx.arg("--supersedes-id")}));}finally{db.close();}});
  dispatch.on("dimensions","definitions",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult({ok:true,definitions:listDimensionDefinitions(db)});}finally{db.close();}});
  dispatch.on("dimensions","members",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult({ok:true,members:listDimensionMembers(db,ctx.arg("--dimension-id"))});}finally{db.close();}});
  dispatch.on("dimensions","plan",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(planDimensionAssignment(db,{journalLineId:Number(ctx.arg("--journal-line-id")),allocations:json(ctx.arg("--allocations"))??[],source:ctx.arg("--source") as any,reviewedImport:ctx.arg("--reviewed-import")==="yes",sourceRef:ctx.arg("--source-ref")}));}finally{db.close();}});
  dispatch.on("dimensions","apply",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(applyDimensionAssignment(db,{...identity(ctx),journalLineId:Number(ctx.arg("--journal-line-id")),allocations:json(ctx.arg("--allocations"))??[],source:ctx.arg("--source") as any,reviewedImport:ctx.arg("--reviewed-import")==="yes",sourceRef:ctx.arg("--source-ref"),planHash:ctx.arg("--plan-hash")!,idempotencyKey:ctx.arg("--idempotency-key")}));}finally{db.close();}});
  dispatch.on("dimensions","replace",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(replaceDimensionAssignment(db,{...identity(ctx),journalLineId:Number(ctx.arg("--journal-line-id")),expectedAssignmentId:Number(ctx.arg("--expected-assignment-id")),allocations:json(ctx.arg("--allocations"))??[],source:ctx.arg("--source") as any,reviewedImport:ctx.arg("--reviewed-import")==="yes",sourceRef:ctx.arg("--source-ref"),planHash:ctx.arg("--plan-hash")!,reason:ctx.arg("--reason")!,idempotencyKey:ctx.arg("--idempotency-key")}));}finally{db.close();}});
  dispatch.on("dimensions","supersede",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(supersedeDimensionAssignment(db,{...identity(ctx),assignmentId:Number(ctx.arg("--assignment-id")),reason:ctx.arg("--reason")!}));}finally{db.close();}});
  dispatch.on("dimensions","list",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult({ok:true,assignments:listDimensionAssignments(db,Number(ctx.arg("--journal-line-id")))});}finally{db.close();}});
  dispatch.on("dimensions","budget-plan",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(planDimensionBudget(db,{accountNo:ctx.arg("--account")!,period:ctx.arg("--period")!,allocations:json(ctx.arg("--allocations"))??[],sourceRef:ctx.arg("--source-ref")!}));}finally{db.close();}});
  dispatch.on("dimensions","budget-apply",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult(applyDimensionBudget(db,{...identity(ctx),accountNo:ctx.arg("--account")!,period:ctx.arg("--period")!,allocations:json(ctx.arg("--allocations"))??[],sourceRef:ctx.arg("--source-ref")!,planHash:ctx.arg("--plan-hash")!,idempotencyKey:ctx.arg("--idempotency-key")}));}finally{db.close();}});
  dispatch.on("dimensions","budgets",ctx=>{const db=openCommandDb(ctx);try{migrate(db);ctx.emitResult({ok:true,budgets:listDimensionBudgets(db)});}finally{db.close();}});
}
