import type { CommandSpec } from "./_shared";
export const bookkeepingBatchSpecs: CommandSpec[] = [
  { key: "bookkeeping-batch plan", usage: "bookkeeping-batch plan --company <path> --company-id <n> --accounting-from <YYYY-MM-DD> --accounting-to <YYYY-MM-DD> --bank-from <YYYY-MM-DD> --bank-to <YYYY-MM-DD>", description: "Beregner kun en deterministisk batchplan og hash; skriver ingen batch-state.", allowedFlags: ["--company", "--company-id", "--accounting-from", "--accounting-to", "--bank-from", "--bank-to"] },
  { key: "bookkeeping-batch persist", usage: "bookkeeping-batch persist --company <path> --run-key <key> --company-id <n> --accounting-from <YYYY-MM-DD> --accounting-to <YYYY-MM-DD> --bank-from <YYYY-MM-DD> --bank-to <YYYY-MM-DD> --actor <actor>", description: "Persisterer den eksakte immutable batchrevision til review.", allowedFlags: ["--company", "--run-key", "--company-id", "--accounting-from", "--accounting-to", "--bank-from", "--bank-to", "--actor"] },
  { key: "bookkeeping-batch dry-run", usage: "bookkeeping-batch dry-run --company <path> --run-key <key> --company-id <n> --accounting-from <YYYY-MM-DD> --accounting-to <YYYY-MM-DD> --bank-from <YYYY-MM-DD> --bank-to <YYYY-MM-DD> --actor <actor>", description: "Persisterer en kanonisk, reviewbar batchrevision med plan-hash.", allowedFlags: ["--company", "--run-key", "--company-id", "--accounting-from", "--accounting-to", "--bank-from", "--bank-to", "--actor"] },
  { key: "bookkeeping-batch approve", usage: "bookkeeping-batch approve --company <path> --run-id <n> --plan-hash <sha256> --actor <actor>", description: "Godkender den eksakte reviewede hash med actor/tid.", allowedFlags: ["--company", "--run-id", "--plan-hash", "--actor"] },
  { key: "bookkeeping-batch apply", usage: "bookkeeping-batch apply --company <path> --run-id <n> --plan-hash <sha256> --confirm --actor <actor>", description: "Anvender eller genoptager kun den eksakt godkendte batchrevision.", allowedFlags: ["--company", "--run-id", "--plan-hash", "--confirm", "--actor"] },
  { key: "bookkeeping-batch status", usage: "bookkeeping-batch status --company <path> --run-id <n>", description: "Viser append-only run-state, item-forsøg og endelig evidens.", allowedFlags: ["--company", "--run-id"] },
];
