import type { CommandSpec } from "./_shared";

const write = ["--workspace", "--confirm"];
export const workspaceRegistrySpecs: CommandSpec[] = [
  { key:"party create", usage:"party create --workspace <dir> --input <json> --confirm yes --actor <id>", description:"Opretter en kanonisk workspace-part med kilde- og review-evidens.", allowedFlags:[...write,"--input"] },
  { key:"party search", usage:"party search --workspace <dir> --company <slug> [--query <text>] [--cursor <n>] [--limit <n>]", description:"Søger deterministisk blandt parter synlige i den angivne virksomhed.", allowedFlags:["--workspace","--company","--query","--cursor","--limit"] },
  { key:"party inspect", usage:"party inspect --workspace <dir> --party-id <id>", description:"Viser en kanonisk parts append-only historik.", allowedFlags:["--workspace","--party-id"] },
  { key:"party link-role", usage:"party link-role --workspace <dir> --party-id <id> --company <slug> --role <role> [--defaults <json>] --confirm yes --actor <id>", description:"Knytter en parts virksomhedslokale rolle og defaults uden at ændre historiske poster.", allowedFlags:[...write,"--party-id","--company","--role","--defaults"] },
  { key:"party propose-merge", usage:"party propose-merge --workspace <dir> --from-party-id <id> --into-party-id <id> --review-assertion <text> --confirm yes --actor <id>", description:"Foreslår, men udfører aldrig automatisk, en kanonisk partssammenslutning.", allowedFlags:[...write,"--from-party-id","--into-party-id","--review-assertion"] },
  { key:"party approve-merge", usage:"party approve-merge --workspace <dir> --from-party-id <id> --proposal-hash <sha256> --confirm yes --actor <id>", description:"Godkender og supersederer den præcise foreslåede partsrelation append-only.", allowedFlags:[...write,"--from-party-id","--proposal-hash"] },
  { key:"corporate-record ingest", usage:"corporate-record ingest --workspace <dir> --file <path> --input <json> --confirm yes --actor <id>", description:"Gemmer uforanderlige governance-bytes og deres SHA-256 uden ledger-effekt.", allowedFlags:[...write,"--file","--input"] },
  { key:"corporate-record list", usage:"corporate-record list --workspace <dir> --company <slug> [--cursor <n>] [--limit <n>]", description:"Lister governance-records der er fuldt synlige i virksomheds-scope.", allowedFlags:["--workspace","--company","--cursor","--limit"] },
  { key:"corporate-record inspect", usage:"corporate-record inspect --workspace <dir> --record-id <id>", description:"Viser record-metadata, scope-links og append-only historik.", allowedFlags:["--workspace","--record-id"] },
  { key:"corporate-record download", usage:"corporate-record download --workspace <dir> --record-id <id>", description:"Læs original bytes efter SHA-256-verifikation (base64 i JSON-output).", allowedFlags:["--workspace","--record-id"] },
  { key:"corporate-record link", usage:"corporate-record link --workspace <dir> --record-id <id> --link-type <type> --link-id <id> --confirm yes --actor <id>", description:"Knytter en record til eksisterende scope append-only.", allowedFlags:[...write,"--record-id","--link-type","--link-id"] },
  { key:"corporate-record enrich", usage:"corporate-record enrich --workspace <dir> --record-id <id> --assertion <text> --confirm yes --actor <id>", description:"Tilføjer auditeret metadata uden at ændre original bytes.", allowedFlags:[...write,"--record-id","--assertion"] },
  { key:"corporate-record supersede", usage:"corporate-record supersede --workspace <dir> --record-id <id> --replacement-record-id <id> --reason <text> --confirm yes --actor <id>", description:"Kæder en rettet governance-record som append-only supersession.", allowedFlags:[...write,"--record-id","--replacement-record-id","--reason"] },
];
