import { canonicalJson } from "./canonical-json";
/** Source-backed operating context (#574).  This is deliberately a small
 * assertion ledger, not a wiki and not an input to accounting decisions. */
import { createHash, randomUUID } from "node:crypto";
import type { Database } from "bun:sqlite";

export const COMPANY_KNOWLEDGE_PREDICATES = ["business_description","operating_status","products_services","revenue_models","markets","customer_types","industry_tags","operational_systems","document_sources","reporting_dimensions","responsible_party","canonical_reference"] as const;
export type CompanyKnowledgePredicate = typeof COMPANY_KNOWLEDGE_PREDICATES[number];
export type KnowledgeSourceKind = "user"|"registry"|"party"|"corporate_record"|"external_snapshot"|"canonical_setting";
export type KnowledgeReviewState = "proposed"|"approved"|"rejected"|"superseded"|"conflict";
export type KnowledgePrincipal = { kind:"user"|"service_account"|"local_operator"; id:string };
const sources: readonly KnowledgeSourceKind[]=["user","registry","party","corporate_record","external_snapshot","canonical_setting"];
const singles=new Set<CompanyKnowledgePredicate>(["business_description","operating_status","canonical_reference"]);
const canonical = canonicalJson;
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
const text=(v:unknown,name:string,max=512)=>{const s=typeof v==="string"?v.trim():"";if(!s||s.length>max)throw new Error(`${name} is required and bounded`);return s;};
const iso=(v:unknown,name:string)=>{const d=new Date(text(v,name,64));if(Number.isNaN(d.valueOf()))throw new Error(`${name} must be ISO date/time`);return d.toISOString();};
const event=(db:Database,id:string,type:Exclude<KnowledgeReviewState,"conflict">,input:{actor:string;principal:KnowledgePrincipal;reason?:string;supersedesAssertionId?:string})=>db.query("INSERT INTO rm_company_knowledge_events(assertion_id,event_type,reason,supersedes_assertion_id,actor,principal_kind,principal_id,created_at) VALUES(?,?,?,?,?,?,?,?)").run(id,type,input.reason?.trim()||null,input.supersedesAssertionId?.trim()||null,text(input.actor,"actor",160),input.principal.kind,text(input.principal.id,"principal id",160),new Date().toISOString());
function current(db:Database,id:string):KnowledgeReviewState {const row=db.query("SELECT event_type FROM rm_company_knowledge_events WHERE assertion_id=? ORDER BY id DESC LIMIT 1").get(id)as{event_type:KnowledgeReviewState}|null;return row?.event_type??"proposed";}
function sourceExists(db:Database,kind:KnowledgeSourceKind,ref:string){if(kind==="party"&&!db.query("SELECT 1 FROM rm_party_events WHERE party_id=? AND event_type='created'").get(ref))throw new Error("source party not found");if(kind==="corporate_record"&&!db.query("SELECT 1 FROM rm_corporate_record_bytes WHERE record_id=?").get(ref))throw new Error("source corporate record not found");}
export type KnowledgeAssertionInput={assertionId?:string;companySlug:string;predicate:CompanyKnowledgePredicate;value:unknown;source:{kind:KnowledgeSourceKind;ref:string};validFrom:string;validToExclusive?:string;certainty?:"confirmed"|"probable"|"uncertain";actor:string;principal:KnowledgePrincipal};
export function proposeCompanyKnowledge(db:Database,input:KnowledgeAssertionInput){if(!COMPANY_KNOWLEDGE_PREDICATES.includes(input.predicate))throw new Error("unsupported knowledge predicate");if(!sources.includes(input.source.kind))throw new Error("unsupported knowledge source");const auditedActor=text(input.actor,"actor",160),principalId=text(input.principal.id,"principal id",160);const valueJson=canonical(input.value);if(valueJson.length>32768)throw new Error("knowledge value is too large");const validFrom=iso(input.validFrom,"validFrom"),validTo=input.validToExclusive?iso(input.validToExclusive,"validToExclusive"):null;if(validTo&&validTo<=validFrom)throw new Error("validToExclusive must be after validFrom");const companySlug=text(input.companySlug,"companySlug",120),sourceRef=text(input.source.ref,"source ref",512),assertionId=input.assertionId?text(input.assertionId,"assertionId",80):`knowledge-${randomUUID()}`;sourceExists(db,input.source.kind,sourceRef);const existing=db.query("SELECT assertion_id FROM rm_company_knowledge_assertions WHERE company_slug=? AND predicate=? AND value_hash=? AND source_kind=? AND source_ref=? AND valid_from=? AND COALESCE(valid_to_exclusive,'')=COALESCE(?, '')").get(companySlug,input.predicate,hash(valueJson),input.source.kind,sourceRef,validFrom,validTo)as{assertion_id:string}|null; if(existing)return inspectCompanyKnowledgeAssertion(db,existing.assertion_id)!;db.transaction(()=>{db.query("INSERT INTO rm_company_knowledge_assertions(assertion_id,company_slug,predicate,value_json,value_hash,source_kind,source_ref,valid_from,valid_to_exclusive,certainty,actor,principal_kind,principal_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(assertionId,companySlug,input.predicate,valueJson,hash(valueJson),input.source.kind,sourceRef,validFrom,validTo,input.certainty??"confirmed",auditedActor,input.principal.kind,principalId,new Date().toISOString());event(db,assertionId,"proposed",{...input,actor:auditedActor,principal:{...input.principal,id:principalId}});})();return inspectCompanyKnowledgeAssertion(db,assertionId)!;}
export function reviewCompanyKnowledge(db:Database,input:{assertionId:string;decision:"approved"|"rejected";reason?:string;actor:string;principal:KnowledgePrincipal}){const assertion=inspectCompanyKnowledgeAssertion(db,text(input.assertionId,"assertionId",80));if(!assertion)throw new Error("knowledge assertion not found");const state=current(db,assertion.assertionId);if(state!=="proposed") {if(state===input.decision)return assertion;throw new Error("knowledge assertion has already been reviewed");} db.transaction(()=>event(db,assertion.assertionId,input.decision,input))();return inspectCompanyKnowledgeAssertion(db,assertion.assertionId)!;}
export function supersedeCompanyKnowledge(db:Database,input:{assertionId:string;replacement:Omit<KnowledgeAssertionInput,"companySlug"|"actor"|"principal">;actor:string;principal:KnowledgePrincipal}){const old=inspectCompanyKnowledgeAssertion(db,text(input.assertionId,"assertionId",80));if(!old)throw new Error("knowledge assertion not found");if(old.reviewState!=="approved")throw new Error("only approved knowledge can be superseded");const replacement=proposeCompanyKnowledge(db,{...input.replacement,companySlug:old.companySlug,actor:input.actor,principal:input.principal});db.transaction(()=>event(db,old.assertionId,"superseded",{...input,supersedesAssertionId:replacement.assertionId}))();return {superseded:inspectCompanyKnowledgeAssertion(db,old.assertionId)!,replacement};}
export function inspectCompanyKnowledgeAssertion(db:Database,id:string){const row=db.query("SELECT * FROM rm_company_knowledge_assertions WHERE assertion_id=?").get(id)as any;if(!row)return null;const history=db.query("SELECT event_type,reason,supersedes_assertion_id,actor,principal_kind,principal_id,created_at FROM rm_company_knowledge_events WHERE assertion_id=? ORDER BY id").all(id);return {assertionId:row.assertion_id,companySlug:row.company_slug,predicate:row.predicate,value:JSON.parse(row.value_json),valueHash:row.value_hash,source:{kind:row.source_kind,ref:row.source_ref},validFrom:row.valid_from,validToExclusive:row.valid_to_exclusive,certainty:row.certainty,actor:row.actor,principal:{kind:row.principal_kind,id:row.principal_id},reviewState:current(db,id),history};}
export function queryCompanyKnowledge(db:Database,input:{companySlug:string;asOf:string;includeProposed?:boolean}){const at=iso(input.asOf,"asOf"),slug=text(input.companySlug,"companySlug",120);const rows=(db.query("SELECT assertion_id FROM rm_company_knowledge_assertions WHERE company_slug=? AND valid_from<=? AND (valid_to_exclusive IS NULL OR valid_to_exclusive>?) ORDER BY predicate,assertion_id").all(slug,at,at)as Array<{assertion_id:string}>).map(r=>inspectCompanyKnowledgeAssertion(db,r.assertion_id)!);const active=rows.filter(r=>r.reviewState==="approved"||(input.includeProposed&&r.reviewState==="proposed"));const conflicts=new Set(active.filter(r=>singles.has(r.predicate)).map(r=>r.predicate).filter(p=>active.filter(r=>r.predicate===p).length>1));return {companySlug:slug,asOf:at,assertions:active.map(a=>({...a,reviewState:conflicts.has(a.predicate)?"conflict":a.reviewState})),conflicts:[...conflicts].sort(),safeForProductBehavior:conflicts.size===0};}
export function companyKnowledgeHistory(db:Database,companySlug:string){return (db.query("SELECT assertion_id FROM rm_company_knowledge_assertions WHERE company_slug=? ORDER BY id").all(text(companySlug,"companySlug",120))as Array<{assertion_id:string}>).map(r=>inspectCompanyKnowledgeAssertion(db,r.assertion_id)!);}
