import { createHash, randomUUID } from "node:crypto";
import type { Database } from "bun:sqlite";
const TYPES=["incorporation","articles","registration","shareholder_register","shareholder_agreement","board_resolution","general_meeting_minutes","capital_or_dividend_resolution","annual_report","auditor_deliverable","intercompany_agreement","ownership_register","share_transfer","authority_letter","bank_mandate","tax_registration","other"] as const;
const STORAGE_TYPES=["articles","registration","board_resolution","ownership_register","share_transfer","authority_letter","bank_mandate","tax_registration","other"] as const;
type RecordType=typeof TYPES[number]; type LinkType="company"|"party"|"ownership"|"disposition"|"legacy_evidence_ref";
const canonical=(v:unknown):string=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(",")}]`:`{${Object.keys(v as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as any)[k])}`).join(",")}}`;
const hash=(v:Uint8Array|string)=>createHash("sha256").update(v).digest("hex");
const requireText=(value:unknown,label:string,max=320)=>{const out=typeof value==="string"?value.trim():"";if(!out||out.length>max)throw new Error(`${label} is required and bounded`);return out;};
const iso=(value:unknown,label:string)=>{const date=new Date(requireText(value,label,40));if(Number.isNaN(date.valueOf()))throw new Error(`${label} must be ISO-8601`);return date.toISOString();};
function storageType(type:RecordType):typeof STORAGE_TYPES[number] { return (STORAGE_TYPES as readonly string[]).includes(type) ? type as typeof STORAGE_TYPES[number] : "other"; }
function append(db:Database,id:string,type:RecordType,event:string,payload:object,actor:string,at:string){const body=canonical(payload),digest=hash(body);db.query("INSERT OR IGNORE INTO rm_corporate_record_events(record_id,event_type,record_type,payload_hash,canonical_payload,actor,created_at) VALUES(?,?,?,?,?,?,?)").run(id,event,storageType(type),digest,body,requireText(actor,"actor",160),at);return digest;}
function assertLinkTarget(db:Database,type:LinkType,id:string) { if(type==="party" && !db.query("SELECT 1 FROM rm_party_events WHERE party_id=? AND event_type='created'").get(id)) throw new Error("linked party does not exist"); }
export function ingestCorporateRecord(db:Database,input:{recordId?:string;type:RecordType;bytes:Uint8Array;filename:string;source:string;receivedAt:string;recordDate?:string;retentionUntil?:string;uploader:string;sensitivity?:"normal"|"confidential"|"restricted";actor:string;links?:Array<{type:LinkType;id:string}>}) { if(!TYPES.includes(input.type))throw new Error("unsupported corporate record type");if(!input.bytes.byteLength)throw new Error("original bytes are required");if(input.bytes.byteLength>16*1024*1024)throw new Error("original bytes exceed 16 MiB bound");const id=input.recordId?requireText(input.recordId,"recordId",64):`record-${randomUUID()}`,sha256=hash(input.bytes),receivedAt=iso(input.receivedAt,"receivedAt"), sensitivity=input.sensitivity??"normal";const payload={type:input.type,sha256,filename:requireText(input.filename,"filename"),source:requireText(input.source,"source"),receivedAt,recordDate:input.recordDate?iso(input.recordDate,"recordDate"):null,retentionUntil:input.retentionUntil?iso(input.retentionUntil,"retentionUntil"):null,uploader:requireText(input.uploader,"uploader",160),sensitivity};db.transaction(()=>{const existing=db.query("SELECT sha256 FROM rm_corporate_record_bytes WHERE record_id=?").get(id)as{sha256:string}|null;if(existing){if(existing.sha256!==sha256)throw new Error("recordId is immutable and already has different bytes");return;}const duplicate=db.query("SELECT record_id FROM rm_corporate_record_bytes WHERE sha256=?").get(sha256)as{record_id:string}|null;if(duplicate)throw new Error("duplicate bytes require explicit shared-record linking, not automatic merge");for(const link of input.links??[])assertLinkTarget(db,link.type,requireText(link.id,"link id",256));db.query("INSERT INTO rm_corporate_record_bytes(record_id,original_bytes,sha256,filename,source,received_at,record_date,retention_until,uploader,sensitivity) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,input.bytes,sha256,payload.filename,payload.source,receivedAt,payload.recordDate,payload.retentionUntil,payload.uploader,sensitivity);append(db,id,input.type,"ingested",payload,input.actor,receivedAt);for(const link of input.links??[])linkCorporateRecord(db,{recordId:id,...link,actor:input.actor,at:receivedAt});})();return inspectCorporateRecord(db,id)!; }
export function linkCorporateRecord(db:Database,input:{recordId:string;type:LinkType;id:string;actor:string;at?:string}) {if(!["company","party","ownership","disposition","legacy_evidence_ref"].includes(input.type))throw new Error("unsupported record link type");const record=inspectCorporateRecord(db,input.recordId);if(!record)throw new Error("corporate record not found");const id=requireText(input.id,"link id",256);assertLinkTarget(db,input.type,id);db.transaction(()=>{const at=input.at?iso(input.at,"at"):new Date().toISOString();db.query("INSERT OR IGNORE INTO rm_corporate_record_links(record_id,link_type,link_id) VALUES(?,?,?)").run(input.recordId,input.type,id);db.query("INSERT OR IGNORE INTO rm_corporate_record_scope_assertions(record_id,scope_kind,scope_id,actor,created_at) VALUES(?,?,?,?,?)").run(input.recordId,input.type,id,requireText(input.actor,"actor",160),at);append(db,input.recordId,record.type,"linked",{type:input.type,id},input.actor,at);})();return inspectCorporateRecord(db,input.recordId)!;}
export function enrichCorporateRecord(db:Database,input:{recordId:string;assertion:string;actor:string;at?:string}){const record=inspectCorporateRecord(db,input.recordId);if(!record)throw new Error("corporate record not found");return append(db,input.recordId,record.type,"enriched",{assertion:requireText(input.assertion,"assertion",2000)},input.actor,input.at?iso(input.at,"at"):new Date().toISOString());}
export function supersedeCorporateRecord(db:Database,input:{recordId:string;replacementRecordId:string;reason:string;actor:string;at?:string}){const record=inspectCorporateRecord(db,input.recordId);if(!record||!inspectCorporateRecord(db,input.replacementRecordId))throw new Error("both corporate records must exist");return append(db,input.recordId,record.type,"superseded",{replacementRecordId:input.replacementRecordId,reason:requireText(input.reason,"reason",1000)},input.actor,input.at?iso(input.at,"at"):new Date().toISOString());}
export function inspectCorporateRecord(db:Database,id:string){const row=db.query("SELECT * FROM rm_corporate_record_bytes WHERE record_id=?").get(id)as any;if(!row)return null;const events=db.query("SELECT event_type,payload_hash,actor,created_at,canonical_payload FROM rm_corporate_record_events WHERE record_id=? ORDER BY id").all(id)as any[];const scopes=db.query("SELECT scope_kind,scope_id FROM rm_corporate_record_scope_assertions WHERE record_id=? ORDER BY scope_kind,scope_id").all(id)as any[];const type=events.length?JSON.parse(events[0].canonical_payload).type ?? "other":"other";return {recordId:id,type,sha256:row.sha256,filename:row.filename,source:row.source,receivedAt:row.received_at,recordDate:row.record_date,retentionUntil:row.retention_until,uploader:row.uploader,sensitivity:row.sensitivity,links:scopes.map(x=>({type:x.scope_kind,id:x.scope_id})),history:events.map(({canonical_payload,...event})=>event)};}
/** Exact scope lookup based on immutable scope assertions, never a mutable
 * convenience table or a paginated list.  Every linked company must be in the
 * authorised set; a record without a company assertion is not company-visible. */
export function inspectVisibleCorporateRecord(db: Database, id: string, companySlugs: ReadonlySet<string>) {
  const record = inspectCorporateRecord(db, id);
  if (!record) return null;
  const companies = record.links.filter((link: any) => link.type === "company").map((link: any) => link.id);
  return companies.length > 0 && companies.every((company: string) => companySlugs.has(company)) ? record : null;
}
export function readCorporateRecordBytes(db:Database,id:string){const row=db.query("SELECT original_bytes,sha256 FROM rm_corporate_record_bytes WHERE record_id=?").get(id)as{original_bytes:Uint8Array;sha256:string}|null;if(!row)throw new Error("corporate record not found");if(hash(row.original_bytes)!==row.sha256)throw new Error("corporate record hash verification failed");return row.original_bytes;}
/** A scoped record is visible only if every declared company is visible. This
 * avoids revealing that an otherwise visible record also concerns a hidden entity. */
export function listCorporateRecords(db:Database,input:{companySlugs?:ReadonlySet<string>;cursor?:number;limit?:number}={}){const limit=Math.min(Math.max(input.limit??25,1),100),cursor=Math.max(input.cursor??0,0);let records=(db.query("SELECT record_id FROM rm_corporate_record_bytes ORDER BY record_id").all()as any[]).map(x=>inspectCorporateRecord(db,x.record_id)!);if(input.companySlugs)records=records.filter(r=>{const companies=r.links.filter((l:any)=>l.type==="company").map((l:any)=>l.id);return companies.length>0&&companies.every((slug:string)=>input.companySlugs!.has(slug));});return {rows:records.slice(cursor,cursor+limit),count:records.length,nextCursor:cursor+limit<records.length?cursor+limit:null};}
