/**
 * Workspace-only evidence lifecycle for a two-sided intercompany disposition.
 * It deliberately opens legal ledgers read-only: normal company booking remains
 * the only way to create or reverse a journal.
 */
import { Database } from "bun:sqlite";
import { createHash, randomUUID } from "node:crypto";
import { companyPaths } from "./paths";
import { companyRootForSlug } from "./workspace";
import { inspectCorporateRecord } from "./corporate-records";
import { inspectParty } from "./party-registry";
import { insertWorkspaceAudit } from "./workspace-control";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const canonical=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonical).join(",")}]`:`{${Object.keys(value as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as any)[k])}`).join(",")}}`;
const text=(value:unknown,name:string,max=160)=>{const result=typeof value==="string"?value.trim().normalize("NFC"):"";if(!result||result.length>max)throw new Error(`${name} is required and bounded`);return result;};
const date=(value:unknown,name:string)=>{const result=text(value,name,10);if(!/^\d{4}-\d\d-\d\d$/.test(result)||Number.isNaN(Date.parse(`${result}T00:00:00Z`)))throw new Error(`${name} must be YYYY-MM-DD`);return result;};
const amount=(value:unknown,name:string)=>{if(typeof value!=="number"||!Number.isFinite(value)||value<=0||Math.round(value*100)!==value*100)throw new Error(`${name} must be a positive two-decimal amount`);return value;};
export type DispositionPrincipal={kind:"user"|"service";id:string};
export type DispositionSide="left"|"right";
export type IntercompanyDisposition={dispositionId:string;type:"invoice"|"reimbursement"|"loan"|"capital"|"dividend"|"repayment"|"other";economicDate:string;amount:number;currency:string;settlementDueDate?:string;partyIds:string[];evidenceRecordIds:string[];left:{companySlug:string;role:string;expectedSide:"receivable"|"payable"};right:{companySlug:string;role:string;expectedSide:"receivable"|"payable"}};

function parse(input:unknown):IntercompanyDisposition {const row=input&&typeof input==="object"&&!Array.isArray(input)?input as any:{};const side=(name:DispositionSide)=>{const item=row[name]??{};const companySlug=text(item.companySlug,`${name}.companySlug`,120);const expectedSide=text(item.expectedSide,`${name}.expectedSide`,20);if(expectedSide!=="receivable"&&expectedSide!=="payable")throw new Error(`${name}.expectedSide must be receivable or payable`);return {companySlug,role:text(item.role,`${name}.role`,80),expectedSide:expectedSide as "receivable"|"payable"};};const left=side("left"),right=side("right");if(left.companySlug===right.companySlug)throw new Error("disposition sides must reference distinct legal companies");if(left.expectedSide===right.expectedSide)throw new Error("disposition sides must be complementary");const type=text(row.type,"type",20);if(!["invoice","reimbursement","loan","capital","dividend","repayment","other"].includes(type))throw new Error("unsupported disposition type");const ids=(value:unknown,name:string)=>{if(!Array.isArray(value)||!value.length||value.length>64)throw new Error(`${name} requires 1 through 64 source-linked references`);const out=value.map((v,i)=>text(v,`${name}[${i}]`,160));if(new Set(out).size!==out.length)throw new Error(`${name} must be unique`);return out.sort();};return {dispositionId:row.dispositionId?text(row.dispositionId,"dispositionId",80):`icd-${randomUUID()}`,type:type as any,economicDate:date(row.economicDate,"economicDate"),amount:amount(row.amount,"amount"),currency:text(row.currency,"currency",3).toUpperCase(),...(row.settlementDueDate?{settlementDueDate:date(row.settlementDueDate,"settlementDueDate")}:{ }),partyIds:ids(row.partyIds,"partyIds"),evidenceRecordIds:ids(row.evidenceRecordIds,"evidenceRecordIds"),left,right};}
function event(db:Database,id:string,type:string,payload:unknown,actor:string,principal:DispositionPrincipal){const previous=db.query("SELECT event_hash FROM rm_intercompany_disposition_events ORDER BY id DESC LIMIT 1").get() as any;const body=canonical(payload),digest=sha(body),at=new Date().toISOString(),hash=sha(canonical({previousHash:previous?.event_hash??null,dispositionId:id,type,payloadHash:digest,actor,principal,at}));db.query("INSERT INTO rm_intercompany_disposition_events(disposition_id,event_type,payload_hash,canonical_payload,actor,principal_kind,principal_id,previous_hash,event_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,type,digest,body,text(actor,"actor",160),principal.kind,text(principal.id,"principal id",160),previous?.event_hash??null,hash,at);insertWorkspaceAudit(db,{createdBy:actor,createdByProgram:"rentemester",eventType:`intercompany_disposition_${type}`,entityType:"intercompany_disposition",entityId:id});return {payloadHash:digest,eventHash:hash};}
function requireRecordAndParties(db:Database,row:IntercompanyDisposition){for(const id of row.partyIds)if(!inspectParty(db,id))throw new Error("disposition party does not exist");for(const id of row.evidenceRecordIds)if(!inspectCorporateRecord(db,id))throw new Error("disposition corporate evidence does not exist");}
function snapshot(workspace:string,companySlug:string,journalEntryId:number){const db=new Database(companyPaths(companyRootForSlug(workspace,companySlug)).db,{readonly:true});try{db.exec("PRAGMA query_only=ON");const company=db.query("SELECT currency FROM companies WHERE id=1").get() as any;const entry=db.query("SELECT id,entry_no,transaction_date,entry_hash,status,reversal_of_entry_id FROM journal_entries WHERE id=?").get(journalEntryId)as any;if(!company||!entry||entry.status!=="posted"||entry.reversal_of_entry_id!=null)throw new Error("journal must be an active posted journal entry");const reversed=db.query("SELECT 1 FROM journal_entries WHERE reversal_of_entry_id=? LIMIT 1").get(journalEntryId);if(reversed)throw new Error("journal entry has been reversed");const lines=db.query("SELECT debit_amount,credit_amount FROM journal_lines WHERE journal_entry_id=?").all(journalEntryId)as any[];const head=db.query("SELECT entry_hash FROM journal_entries ORDER BY id DESC LIMIT 1").get()as any;return {currency:String(company.currency).toUpperCase(),entry,lines,ledgerHeadHash:head?.entry_hash??null};}finally{db.close();}}
function state(db:Database,id:string){const row=db.query("SELECT canonical_payload,payload_hash FROM rm_intercompany_dispositions WHERE disposition_id=?").get(id)as any;if(!row)return null;const events=db.query("SELECT event_type,actor,principal_kind,principal_id,payload_hash,created_at FROM rm_intercompany_disposition_events WHERE disposition_id=? ORDER BY id").all(id)as any[];const links=db.query("SELECT side,company_slug,journal_entry_id,journal_entry_no,journal_entry_hash,ledger_head_hash,linked_at FROM rm_intercompany_disposition_journal_links WHERE disposition_id=? ORDER BY side").all(id)as any[];const terminal=["rejected","cancelled","settled","superseded"].find(type=>events.some(event=>event.event_type===type));let status=terminal??(events.some(event=>event.event_type==="approved")?"approved":"proposed");if(status==="approved"){if(links.length===1)status="partly_posted";if(links.length===2)status="posted";}return {disposition:JSON.parse(row.canonical_payload),payloadHash:row.payload_hash,status,events,links};}
export function proposeIntercompanyDisposition(db:Database,input:unknown,audit:{actor:string;principal:DispositionPrincipal}){const value=parse(input);requireRecordAndParties(db,value);return db.transaction(()=>{const exists=state(db,value.dispositionId);const payload=canonical(value);if(exists){if(exists.payloadHash===sha(payload)&&exists.status==="proposed")return exists;throw new Error("disposition id already exists with a different or completed lifecycle");}db.query("INSERT INTO rm_intercompany_dispositions(disposition_id,canonical_payload,payload_hash,created_at) VALUES(?,?,?,?)").run(value.dispositionId,payload,sha(payload),new Date().toISOString());event(db,value.dispositionId,"proposed",value,audit.actor,audit.principal);return state(db,value.dispositionId)!;}).immediate();}
export function approveIntercompanyDisposition(db:Database,id:string,payloadHash:string,audit:{actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(id,"disposition id",80));if(!current||current.status!=="proposed"||current.payloadHash!==payloadHash)throw new Error("exact proposed disposition was not found");const proposer=current.events[0];if(proposer.principal_kind===audit.principal.kind&&proposer.principal_id===audit.principal.id)throw new Error("disposition approval requires a distinct stable principal");event(db,id,"approved",{payloadHash},audit.actor,audit.principal);return state(db,id)!;}).immediate();}
export function linkIntercompanyDispositionJournal(db:Database,workspace:string,input:{dispositionId:string;payloadHash:string;side:DispositionSide;journalEntryId:number;expectedLedgerHeadHash:string|null;actor:string;principal:DispositionPrincipal}){return db.transaction(()=>{const current=state(db,text(input.dispositionId,"disposition id",80));if(!current||current.status!=="approved"&&current.status!=="partly_posted")throw new Error("only approved dispositions can link journals");if(current.payloadHash!==input.payloadHash)throw new Error("exact disposition hash is required");if(current.links.some((link:any)=>link.side===input.side)){const old=current.links.find((link:any)=>link.side===input.side)!;if(old.journal_entry_id===input.journalEntryId)return current;throw new Error("disposition side already has an immutable journal link");}const expected=current.disposition[input.side];const actual=snapshot(workspace,expected.companySlug,input.journalEntryId);if(actual.ledgerHeadHash!==input.expectedLedgerHeadHash)throw new Error("ledger head changed; refresh before linking");if(actual.currency!==current.disposition.currency)throw new Error("journal company currency does not match disposition currency");if(actual.entry.transaction_date!==current.disposition.economicDate)throw new Error("journal date does not match disposition economic date");const expectedAmount=Math.round(current.disposition.amount*100);const matched=actual.lines.some((line:any)=>Math.round(Number(expected.expectedSide==="receivable"?line.debit_amount:line.credit_amount)*100)===expectedAmount);if(!matched)throw new Error("journal does not contain the expected amount on the expected disposition side");db.query("INSERT INTO rm_intercompany_disposition_journal_links(disposition_id,side,company_slug,journal_entry_id,journal_entry_no,journal_entry_hash,ledger_head_hash,linked_at,actor,principal_kind,principal_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(input.dispositionId,input.side,expected.companySlug,input.journalEntryId,actual.entry.entry_no,actual.entry.entry_hash,actual.ledgerHeadHash,new Date().toISOString(),text(input.actor,"actor",160),input.principal.kind,text(input.principal.id,"principal id",160));event(db,input.dispositionId,"exception",{kind:"one_sided_posting",side:input.side},input.actor,input.principal);if(current.links.length===1)event(db,input.dispositionId,"approved",{payloadHash:input.payloadHash,linked:true},input.actor,input.principal);return state(db,input.dispositionId)!;}).immediate();}
export function inspectIntercompanyDisposition(db:Database,id:string){return state(db,id);}
