import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { migrate, openDb } from "../../src/core/db";
import { applyDimensionAssignment, changeDimensionDefinition, changeDimensionMember, createDimensionDefinition, createDimensionMember, listDimensionDefinitions, listDimensionMembers, planDimensionAssignment, supersedeDimensionAssignment } from "../../src/core/accounting-dimensions";

const roots:string[]=[];
function setup() { const root=mkdtempSync(join(tmpdir(),"rm-dimensions-"));roots.push(root); const db=openDb(join(root,"ledger.db"));migrate(db); db.run("INSERT INTO accounts(account_no,name,type,normal_balance) VALUES('9999','Synthetic','expense','debit')"); const account=db.query("SELECT id FROM accounts WHERE account_no='9999'").get() as any; const entry=db.query("INSERT INTO journal_entries(entry_no,transaction_date,text,rule_version,entry_hash) VALUES('E-1','2026-01-01','test','test',?) RETURNING id").get("a".repeat(64)) as any; const line=db.query("INSERT INTO journal_lines(journal_entry_id,account_id,debit_amount,credit_amount,currency) VALUES(?,?,12.34,0,'DKK') RETURNING id").get(entry.id,account.id) as any; return {db,lineId:line.id}; }
afterEach(()=>{ for (const root of roots.splice(0)) rmSync(root,{recursive:true,force:true}); });
const identity={actor:"user:reviewer",principal:"user:reviewer",confirm:true};
describe("#589 accounting dimensions",()=>{
  test("keeps the legal journal unchanged and requires supersession before reclassification",()=>{ const {db,lineId}=setup(); expect(createDimensionDefinition(db,{...identity,dimensionId:"project",kind:"project",name:"Project"}).ok).toBeTrue(); expect(createDimensionMember(db,{...identity,dimensionId:"project",memberId:"a",name:"A"}).ok).toBeTrue();expect(createDimensionMember(db,{...identity,dimensionId:"project",memberId:"b",name:"B"}).ok).toBeTrue(); const before=db.query("SELECT debit_amount,credit_amount,currency FROM journal_lines WHERE id=?").get(lineId); const allocation={dimensionId:"project",memberId:"a",amountMinor:1234,currency:"DKK"};const plan=planDimensionAssignment(db,{journalLineId:lineId,allocations:[allocation]}); expect(plan.ok).toBeTrue(); if(!plan.ok)return; const applied=applyDimensionAssignment(db,{...identity,journalLineId:lineId,allocations:[allocation],planHash:plan.plan.planHash});expect(applied).toMatchObject({ok:true,idempotent:false});expect(applyDimensionAssignment(db,{...identity,journalLineId:lineId,allocations:[allocation],planHash:plan.plan.planHash})).toMatchObject({ok:true,idempotent:true});const replacement={...allocation,memberId:"b"};const replacementPlan=planDimensionAssignment(db,{journalLineId:lineId,allocations:[replacement]});if(!replacementPlan.ok)throw new Error("replacement plan");expect(applyDimensionAssignment(db,{...identity,journalLineId:lineId,allocations:[replacement],planHash:replacementPlan.plan.planHash})).toEqual({ok:false,errors:["CURRENT_ASSIGNMENT_REQUIRES_SUPERSESSION"]}); expect(db.query("SELECT debit_amount,credit_amount,currency FROM journal_lines WHERE id=?").get(lineId)).toEqual(before); expect(()=>db.run("UPDATE accounting_dimension_assignment_events SET actor='x'")).toThrow("append-only"); db.close(); });
  test("rejects incomplete, overallocated, mixed currency, inactive and unreviewed imported assignments",()=>{ const {db,lineId}=setup(); createDimensionDefinition(db,{...identity,dimensionId:"project",kind:"project",name:"Project"});createDimensionMember(db,{...identity,dimensionId:"project",memberId:"old",name:"Old",status:"inactive"}); createDimensionMember(db,{...identity,dimensionId:"project",memberId:"new",name:"New"}); const make=(allocations:any[],source?:any,reviewedImport?:boolean)=>planDimensionAssignment(db,{journalLineId:lineId,allocations,source,reviewedImport}); expect(make([{dimensionId:"project",memberId:"new",amountMinor:1233,currency:"DKK"}])).toEqual({ok:false,errors:["ALLOCATION_DOES_NOT_RECONCILE"]}); expect(make([{dimensionId:"project",memberId:"new",amountMinor:1235,currency:"DKK"}])).toEqual({ok:false,errors:["ALLOCATION_DOES_NOT_RECONCILE"]}); expect(make([{dimensionId:"project",memberId:"new",amountMinor:1234,currency:"EUR"}])).toEqual({ok:false,errors:["INVALID_ALLOCATION"]}); expect(make([{dimensionId:"project",memberId:"old",amountMinor:1234,currency:"DKK"}])).toEqual({ok:false,errors:["INACTIVE_MEMBER_REQUIRES_REVIEWED_OVERRIDE"]}); expect(make([{dimensionId:"project",memberId:"new",amountMinor:1234,currency:"DKK"}],"imported",false)).toEqual({ok:false,errors:["IMPORTED_PROVENANCE_REQUIRES_REVIEW"]}); db.close(); });
  test("supersedes without rewriting the journal",()=>{ const {db,lineId}=setup();createDimensionDefinition(db,{...identity,dimensionId:"cost-centre",kind:"cost-centre",name:"Cost centre"});createDimensionMember(db,{...identity,dimensionId:"cost-centre",memberId:"one",name:"One"});const allocation={dimensionId:"cost-centre",memberId:"one",amountMinor:1234,currency:"DKK"};const plan=planDimensionAssignment(db,{journalLineId:lineId,allocations:[allocation]});if(!plan.ok)throw new Error("plan");const applied=applyDimensionAssignment(db,{...identity,journalLineId:lineId,allocations:[allocation],planHash:plan.plan.planHash});if(!applied.ok)throw new Error("apply");expect(supersedeDimensionAssignment(db,{...identity,assignmentId:applied.id,reason:"classification corrected"})).toMatchObject({ok:true});expect(db.query("SELECT count(*) n FROM current_accounting_dimension_assignments").get()).toEqual({n:0});db.close(); });
  test("enforces member effective dates and imported source provenance",()=>{const {db,lineId}=setup();createDimensionDefinition(db,{...identity,dimensionId:"project",kind:"project",name:"Project"});createDimensionMember(db,{...identity,dimensionId:"project",memberId:"future",name:"Future",effectiveFrom:"2026-02-01"});const allocation={dimensionId:"project",memberId:"future",amountMinor:1234,currency:"DKK"};expect(planDimensionAssignment(db,{journalLineId:lineId,allocations:[allocation]})).toEqual({ok:false,errors:["MEMBER_NOT_EFFECTIVE_ON_JOURNAL_DATE"]});createDimensionMember(db,{...identity,dimensionId:"project",memberId:"current",name:"Current",effectiveFrom:"2025-01-01",effectiveTo:"2026-12-31"});const current={...allocation,memberId:"current"};expect(planDimensionAssignment(db,{journalLineId:lineId,allocations:[current],source:"imported",reviewedImport:true})).toEqual({ok:false,errors:["IMPORTED_PROVENANCE_REQUIRES_REVIEW"]});expect(planDimensionAssignment(db,{journalLineId:lineId,allocations:[current],source:"imported",reviewedImport:true,sourceRef:"dinero:project:synthetic"}).ok).toBeTrue();db.close();});
  test("keeps stable IDs and historical labels through lifecycle events",()=>{const {db}=setup();createDimensionDefinition(db,{...identity,dimensionId:"project",kind:"project",name:"Projects"});createDimensionDefinition(db,{...identity,dimensionId:"project-next",kind:"project",name:"Projects next"});createDimensionMember(db,{...identity,dimensionId:"project",memberId:"old",name:"Original"});createDimensionMember(db,{...identity,dimensionId:"project",memberId:"new",name:"Replacement"});expect(changeDimensionDefinition(db,"rename",{...identity,dimensionId:"project",name:"Projects 2026"})).toMatchObject({ok:true});expect(changeDimensionDefinition(db,"supersede",{...identity,dimensionId:"project",supersedesId:"project-next"})).toMatchObject({ok:true});expect(changeDimensionMember(db,"rename",{...identity,dimensionId:"project",memberId:"old",name:"Historic"})).toMatchObject({ok:true});expect(changeDimensionMember(db,"deactivate",{...identity,dimensionId:"project",memberId:"old"})).toMatchObject({ok:true});expect(changeDimensionMember(db,"supersede",{...identity,dimensionId:"project",memberId:"old",supersedesId:"new"})).toMatchObject({ok:true});expect(listDimensionDefinitions(db).map((r:any)=>r.name)).toContain("Projects");expect(listDimensionMembers(db,"project").map((r:any)=>r.name)).toContain("Original");expect(db.query("SELECT status FROM current_accounting_dimension_members WHERE dimension_id='project' AND member_id='old'").get()).toEqual({status:"superseded"});db.close();});
});
