import { describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { createHmac } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  createBetterAuthRequestProvider,
  createBetterAuthRuntime,
  createPrivateBootstrapService,
  openWorkspaceBetterAuth,
  assertInjectedBetterAuthSecret,
} from "../../src/server/better-auth";
import {
  AuthEmailDeliveryDisabledError,
  AuthEmailDeliveryError,
  createDisabledAuthEmailSender,
  createFakeAuthEmailSender,
  createHttpJsonV1AuthEmailSender,
} from "../../src/server/auth-email";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import {
  AUTH_SESSION_EXPIRES_IN_SECONDS,
  AUTH_SESSION_FRESH_AGE_SECONDS,
} from "../../src/server/security-policy";

/** Canonical unpadded base64url for 32 cryptographically generated bytes. */
const TEST_SECRET = "I0UjL6i0-ScgvjfIgzMKJxPQyDpPXwg2mMKdLW3Y3WQ";
const ROTATED_TEST_SECRET = "KH5Zcv2oA_oM9kOskr7DcGUGRn9PXsTdxnSqjx083ag";
const TEST_ORIGIN = "http://127.0.0.1:4319";

function temporaryWorkspace(): string {
  return mkdtempSync(join(tmpdir(), "rentemester-better-auth-"));
}

describe("Better Auth workspace foundation", () => {
  test("uses Bun Request handler compatibility and rejects public email/password sign-up", async () => {
    const workspace = temporaryWorkspace();
    try {
      const runtime = openWorkspaceBetterAuth(workspace, {
        secret: TEST_SECRET,
        trustedOrigins: [TEST_ORIGIN],
        baseURL: TEST_ORIGIN,
      });
      const response = await runtime.auth.handler(new Request(`${TEST_ORIGIN}/api/auth/sign-up/email`, {
        method: "POST",
        headers: { "content-type": "application/json", origin: TEST_ORIGIN },
        body: JSON.stringify({ name: "Synthetic", email: "synthetic@example.test", password: "a-password-with-12" }),
      }));
      expect(response.status).toBe(400);
      const db = openWorkspaceControlDb(workspace);
      expect(db.query('SELECT COUNT(*) AS count FROM "user"').get()).toEqual({ count: 0 });
      db.close();
      runtime.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("keeps the reviewed security configuration explicit", () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const auth = createBetterAuthRuntime(db, {
        secret: TEST_SECRET,
        trustedOrigins: [TEST_ORIGIN],
        baseURL: TEST_ORIGIN,
        useSecureCookies: true,
      });
      expect(auth.options.emailAndPassword).toMatchObject({
        enabled: true,
        disableSignUp: true,
        minPasswordLength: 12,
        requireEmailVerification: true,
        revokeSessionsOnPasswordReset: true,
      });
      expect(auth.options.session?.cookieCache?.enabled).toBe(false);
      expect(auth.options.session).toMatchObject({
        expiresIn: AUTH_SESSION_EXPIRES_IN_SECONDS,
        freshAge: AUTH_SESSION_FRESH_AGE_SECONDS,
        disableSessionRefresh: true,
      });
      expect(auth.options.rateLimit).toMatchObject({ enabled: true, storage: "database" });
      expect(JSON.stringify(auth.options)).toContain('"useSecureCookies":true');
      expect(auth.options.plugins?.map((plugin: { id: string }) => plugin.id)).toEqual(["two-factor", "api-key"]);
      expect(JSON.stringify(auth.options)).toContain('"storeBackupCodes":"encrypted"');
      expect(auth.options.advanced).toMatchObject({ disableOriginCheck: false, disableCSRFCheck: false });
      expect(auth.options.secrets).toEqual([{ version: 1, value: TEST_SECRET }]);
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("uses Better Auth 1.7 versioned secrets with the first key active and a fixed proxy header", () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const options = {
        secret: ROTATED_TEST_SECRET,
        secrets: [
          { version: 2, value: ROTATED_TEST_SECRET },
          { version: 1, value: TEST_SECRET },
        ],
        legacySecret: TEST_SECRET,
        trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        deploymentMode: "hosted" as const,
        useSecureCookies: true,
        rateLimitIpHeader: "x-real-ip" as const,
      };
      const auth = createBetterAuthRuntime(db, options);
      expect(auth.options.secrets).toEqual(options.secrets);
      expect(auth.options.advanced?.ipAddress).toEqual({ ipAddressHeaders: ["x-real-ip"] });
      expect(JSON.stringify(auth.options.advanced)).not.toContain("trustedProxies");
      const bootstrap = createPrivateBootstrapService(db, options);
      expect(bootstrap.canonicalEmailHash("rotation@example.test")).toBe(
        createHmac("sha256", ROTATED_TEST_SECRET)
          .update("rentemester-workspace-bootstrap-email-v1\0rotation@example.test")
          .digest("hex"),
      );
      expect(() => createBetterAuthRuntime(db, {
        ...options, rateLimitIpHeader: undefined,
      })).toThrow("reverse-proxy client IP header");
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("records the active versioned identity-HMAC key id in telemetry", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const auth = createBetterAuthRuntime(db, { secret: ROTATED_TEST_SECRET, secrets: [{ version: 7, value: ROTATED_TEST_SECRET }, { version: 1, value: TEST_SECRET }], trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN });
      await auth.handler(new Request(`${TEST_ORIGIN}/api/auth/sign-in/email`, { method: "POST", headers: { origin: TEST_ORIGIN, "content-type": "application/json" }, body: JSON.stringify({ email: "rotation@example.test", password: "wrong-password" }) }));
      expect(db.query("SELECT identity_key_version FROM rm_workspace_auth_telemetry_events").all()).toEqual([{ identity_key_version: 7 }]);
      db.close();
    } finally { rmSync(workspace, { recursive: true, force: true }); }
  });

  test("requires an injected high-entropy secret, explicit origins, and secure hosted cookies", () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      expect(() => createBetterAuthRuntime(db, {
        secret: "too-short",
        trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
      })).toThrow("must be injected");
      expect(() => createBetterAuthRuntime(db, {
        secret: TEST_SECRET, trustedOrigins: [], baseURL: TEST_ORIGIN,
      })).toThrow("explicit trusted origin");
      expect(() => createBetterAuthRuntime(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        deploymentMode: "hosted",
      })).toThrow("useSecureCookies");
      expect(() => assertInjectedBetterAuthSecret("abcdefghijklabcdefghijklabcdefghijkl")).toThrow("canonical base64url");
      expect(() => assertInjectedBetterAuthSecret("correct-horse-battery-staple")).toThrow("canonical base64url");
      expect(() => assertInjectedBetterAuthSecret("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")).not.toThrow();
      expect(() => assertInjectedBetterAuthSecret(TEST_SECRET)).not.toThrow();
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("disabled email fails closed and the in-memory sender is test-only without I/O", async () => {
    const disabled = createDisabledAuthEmailSender();
    await expect(disabled.send({
      kind: "verification", recipient: "synthetic@example.test", url: "https://example.test/v", token: "secret",
    })).rejects.toBeInstanceOf(AuthEmailDeliveryDisabledError);

    const fake = createFakeAuthEmailSender();
    await fake.send({
      kind: "password-reset", recipient: "synthetic@example.test", url: "https://example.test/r", token: "secret",
    });
    expect(fake.messages).toEqual([{
      kind: "password-reset", recipient: "synthetic@example.test", url: "https://example.test/r", token: "secret",
    }]);
  });

  test("Better Auth callbacks await delivery and propagate only the sanitized gateway failure", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      let resolveDelivery: (() => void) | undefined;
      let delivered = false;
      const auth = createBetterAuthRuntime(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        emailSender: {
          send: async () => await new Promise<void>((resolve) => {
            resolveDelivery = () => { delivered = true; resolve(); };
          }),
        },
      });
      const callback = auth.options.emailVerification!.sendVerificationEmail!;
      const pending = callback({
        user: { email: "synthetic@example.test" } as never,
        url: "https://cockpit.example.test/verify?token=private", token: "private",
      });
      await Promise.resolve();
      expect(delivered).toBe(false);
      resolveDelivery!();
      await pending;
      expect(delivered).toBe(true);

      const failingAuth = createBetterAuthRuntime(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        emailSender: createHttpJsonV1AuthEmailSender({
          url: "https://gateway.example.test/send", bearerToken: "private", from: "auth@example.test",
          idempotencySecret: TEST_SECRET,
        }, { async fetch() { return new Response("provider private detail", { status: 400 }); } }),
      });
      await expect(failingAuth.options.emailAndPassword!.sendResetPassword!({
        user: { email: "synthetic@example.test" } as never,
        url: "https://cockpit.example.test/reset?token=private", token: "private",
      })).rejects.toEqual(new AuthEmailDeliveryError());
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("private bootstrap creates a credential identity without a session", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const bootstrap = createPrivateBootstrapService(db, {
        secret: TEST_SECRET,
        trustedOrigins: [TEST_ORIGIN],
        baseURL: TEST_ORIGIN,
        emailSender: createFakeAuthEmailSender(),
      });
      const result = await bootstrap.createFirstIdentity({
        name: "Bootstrap User", email: "bootstrap@example.test", password: "a-password-with-12",
      });
      expect(result.userId.length).toBeGreaterThan(0);
      expect(db.query('SELECT COUNT(*) AS count FROM "account"').get()).toEqual({ count: 1 });
      expect(db.query('SELECT COUNT(*) AS count FROM "session"').get()).toEqual({ count: 0 });
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("records actual Better Auth handler sign-in attempts append-only without persisting credentials", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const bootstrap = createPrivateBootstrapService(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN, emailSender: createFakeAuthEmailSender(),
      });
      await bootstrap.createFirstIdentity({ name: "Audit", email: "audit@example.test", password: "a-password-with-12" });
      const auth = createBetterAuthRuntime(db, { secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN });
      const response = await auth.handler(new Request(`${TEST_ORIGIN}/api/auth/sign-in/email`, {
        method: "POST", headers: { origin: TEST_ORIGIN, "content-type": "application/json" },
        body: JSON.stringify({ email: "audit@example.test", password: "wrong-password" }),
      }));
      expect(response.status).toBeGreaterThanOrEqual(400);
      const rows = db.query("SELECT endpoint, outcome, identity_hash, user_id, session_id, identity_key_version FROM rm_workspace_auth_telemetry_events").all() as Array<Record<string, unknown>>;
      expect(rows).toEqual([expect.objectContaining({ endpoint: "sign-in-email", outcome: "rejected", user_id: null, session_id: null, identity_hash: expect.stringMatching(/^[a-f0-9]{64}$/), identity_key_version: 1 })]);
      expect(JSON.stringify(rows)).not.toContain("audit@example.test");
      expect(JSON.stringify(rows)).not.toContain("wrong-password");
      expect(() => db.run("UPDATE rm_workspace_auth_telemetry_events SET outcome = 'accepted'")).toThrow("append-only");
      expect(() => db.run("DELETE FROM rm_workspace_auth_telemetry_events")).toThrow("append-only");
      db.close();
    } finally { rmSync(workspace, { recursive: true, force: true }); }
  });

  test("a sign-up delivery callback may leave an identity row, so recovery must use lookup plus explicit resend", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const bootstrap = createPrivateBootstrapService(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        emailSender: { async send() { throw new AuthEmailDeliveryError(); } },
      });
      // Better Auth currently schedules this callback in the background during
      // sign-up. The credential row is durable even though delivery is not a
      // confirmed outcome; bootstrap saga code must therefore explicitly
      // resend before recording its mail-confirmed state.
      await bootstrap.createFirstIdentity({
        name: "Uncertain Delivery", email: "uncertain@example.test", password: "a-password-with-12",
      });
      expect(await bootstrap.findIdentityByCanonicalEmail("UNCERTAIN@example.test")).toMatchObject({ userId: expect.any(String) });
      expect(db.query('SELECT COUNT(*) AS count FROM "user"').get()).toEqual({ count: 1 });
      await expect(bootstrap.resendVerification("uncertain@example.test")).rejects.toBeInstanceOf(AuthEmailDeliveryError);
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("background email failures emit only an allowlisted operational event", async () => {
    const workspace = temporaryWorkspace();
    const capturedEvents: unknown[] = [];
    const consoleOutput: unknown[][] = [];
    const originalWarn = console.warn;
    const originalError = console.error;
    const originalLog = console.log;
    try {
      console.warn = (...args: unknown[]) => { consoleOutput.push(args); };
      console.error = (...args: unknown[]) => { consoleOutput.push(args); };
      console.log = (...args: unknown[]) => { consoleOutput.push(args); };
      const db = openWorkspaceControlDb(workspace);
      let attemptedMessage: { recipient: string; url: string; token: string } | undefined;
      const bootstrap = createPrivateBootstrapService(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        operationalLogger: { emit(event) { capturedEvents.push(event); } },
        emailSender: {
          async send(message) {
            attemptedMessage = message;
            throw new Error("provider path https://provider.example.test/private-send stack-private-detail");
          },
        },
      });

      // Better Auth catches this sign-up callback failure in its background
      // runner. The custom logger must not receive its Error or callback data.
      await bootstrap.createFirstIdentity({
        name: "Logger Test", email: "leak@example.test", password: "a-password-with-12",
      });
      expect(capturedEvents).toEqual([{
        component: "better-auth", event: "better_auth_error", level: "error",
      }]);
      const output = JSON.stringify({ capturedEvents, consoleOutput });
      for (const sensitive of [
        TEST_SECRET,
        "leak@example.test",
        "https://provider.example.test/private-send",
        "stack-private-detail",
        attemptedMessage!.url,
        attemptedMessage!.token,
      ]) expect(output).not.toContain(sensitive);
      db.close();
    } finally {
      console.warn = originalWarn;
      console.error = originalError;
      console.log = originalLog;
      rmSync(workspace, { recursive: true, force: true });
    }
  });

  test("request provider uses Better Auth's server session API once per call", async () => {
    const workspace = temporaryWorkspace();
    try {
      const db = openWorkspaceControlDb(workspace);
      const bootstrap = createPrivateBootstrapService(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
        emailSender: createFakeAuthEmailSender(),
      });
      await bootstrap.createFirstIdentity({
        name: "Session User", email: "session@example.test", password: "a-password-with-12",
      });
      const auth = createBetterAuthRuntime(db, {
        secret: TEST_SECRET, trustedOrigins: [TEST_ORIGIN], baseURL: TEST_ORIGIN,
      });
      const provider = createBetterAuthRequestProvider(auth);
      expect(await provider.getSession(new Request(`${TEST_ORIGIN}/api/health`))).toBeNull();
      db.close();
    } finally {
      rmSync(workspace, { recursive: true, force: true });
    }
  });
});
