import { Database } from "bun:sqlite";
import { describe, expect, test } from "bun:test";
import { migrate } from "../../src/core/db";
import { seedAccounts, postJournalEntry } from "../../src/core/ledger";
import { addBankAccount } from "../../src/core/bank";
import { linkBankTransactionToJournal } from "../../src/core/bank-journal-reconciliation";
import { buildBookkeepingWorkbench } from "../../src/core/bookkeeping-workbench";
import { approvePostingRuleVersion, createManualPostingProposal } from "../../src/core/posting-rules";

function fixture(){const db=new Database(":memory:");migrate(db);seedAccounts(db);db.exec("INSERT INTO companies(id,name) VALUES(1,'Synthetic')");const account=addBankAccount(db,{name:"Bank",slug:"bank",ledgerAccountNo:"2000"}).account!;const opening=postJournalEntry(db,{transactionDate:"2026-01-01",text:"Opening",createdBy:"agent:test",lines:[{accountNo:"2000",debitAmount:1},{accountNo:"5000",creditAmount:1}]});db.query("INSERT INTO opening_balances(cut_over_date,journal_entry_id,journal_entry_no) VALUES(?,?,?)").run("2026-01-01",opening.entryId,"OPENING");for(const [id,date,text,amount] of [[1,"2026-01-02","Missing evidence",-12],[2,"2026-01-03","Already booked",-13],[3,"2025-12-30","Old system",-14]] as const)db.query("INSERT INTO bank_transactions(id,transaction_date,text,amount,currency,transaction_hash,bank_account_id) VALUES(?,?,?,?,?,?,?)").run(id,date,text,amount,"DKK",`bank-${id}`,account.id);const journal=postJournalEntry(db,{transactionDate:"2026-01-03",text:"Booked",createdBy:"agent:test",lines:[{accountNo:"2000",creditAmount:13},{accountNo:"7000",debitAmount:13}]});expect(linkBankTransactionToJournal(db,{bankTransactionId:2,journalEntryId:Number(journal.entryId),matchMethod:"manual-review",createdBy:"agent:test"}).ok).toBe(true);return db;}
describe("bookkeeping workbench",()=>{
 test("shows each unresolved post once and excludes reconciled and pre-cut-over rows",()=>{const db=fixture();const result=buildBookkeepingWorkbench(db,{from:"2025-12-01",to:"2026-01-31"});expect(result.rows.map(row=>row.bankTransactionId)).toEqual([1]);expect(result.rows[0]?.status).toBe("missingDocument");expect(result.counts.missingDocument).toBe(1);expect(result.state).toBe("available");db.close();});
 test("is deterministic, paginated, and distinguishes zero from unavailable",()=>{const db=fixture();const one=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",limit:1});const two=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",limit:1});expect(two).toEqual(one);expect(one.page.total).toBe(1);const zero=buildBookkeepingWorkbench(db,{from:"2027-01-01",to:"2027-01-31"});expect(zero.state).toBe("zero");expect(zero.rows).toEqual([]);db.close();});
 test("returns unavailable without querying a ledger whose required schema is absent",()=>{const db=new Database(":memory:");const result=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31"});expect(result).toMatchObject({state:"unavailable",completeness:{reasonCode:"schema_not_current"},rows:[],plan:null,population:{total:0}});db.close();});
 test("marks an unreadable reviewed revision incomplete instead of hiding the failed projection",()=>{const db=fixture();db.query("INSERT INTO bookkeeping_batch_runs(run_key,company_id,accounting_from,accounting_to,bank_from,bank_to,plan_hash,plan_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run("corrupt-review",1,"2026-01-01","2026-01-31","2026-01-01","2026-01-31","d".repeat(64),"{}","2026-01-10T00:00:00.000Z");const run=(db.query("SELECT id FROM bookkeeping_batch_runs WHERE run_key='corrupt-review'").get()as{id:number}).id;db.query("INSERT INTO bookkeeping_batch_revisions(run_id,revision_hash,candidate_set_hash,plan_json,planner_kind,planner_subject_id,planner_actor,created_at) VALUES(?,?,?,?,?,?,?,?)").run(run,"d".repeat(64),"c".repeat(64),"{}","user","planner","agent:test","2026-01-10T00:00:00.000Z");const result=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31"});expect(result).toMatchObject({state:"incomplete",completeness:{reasonCode:"reviewed_plan_unreadable"},population:{total:1,blockers:1}});db.close();});
 test("status filters expose both selected and whole-population counts",()=>{const db=fixture();db.query("INSERT INTO bank_transactions(id,transaction_date,text,amount,currency,transaction_hash,bank_account_id) SELECT 4,'2026-01-04','Second missing',-20,'DKK','bank-4',id FROM bank_accounts ORDER BY id LIMIT 1").run();const result=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",status:"missingDocument",limit:1});expect(result.page).toMatchObject({total:2,limit:1,nextCursor:1});expect(result.selection).toEqual({total:2,ready:0,blockers:2});expect(result.population).toEqual({total:2,ready:0,blockers:2});expect(result.counts.missingDocument).toBe(2);db.close();});
 test("amount and currency search are deterministic facets",()=>{const db=fixture();const matched=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",search:"-12 DKK"});const missed=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",search:"-13 DKK"});expect(matched.rows.map(row=>row.bankTransactionId)).toEqual([1]);expect(matched.selection).toEqual({total:1,ready:0,blockers:1});expect(missed.rows).toEqual([]);expect(missed.population.total).toBe(1);db.close();});
 test("uses the canonical party link and explicit unresolved state rather than sender name",()=>{const db=fixture();db.query("INSERT INTO documents(id,source,sha256_hash,document_type,currency,invoice_date,amount_inc_vat,vat_amount,sender_name,payment_details) VALUES(3,'test',?,'purchase_sale','DKK','2026-01-05',50,10,'Untrusted sender text','CANONICAL-REF')").run("a".repeat(64));db.query("INSERT INTO bank_transactions(id,transaction_date,text,amount,currency,transaction_hash,bank_account_id) SELECT 5,'2026-01-05','CANONICAL-REF',-50,'DKK','bank-5',id FROM bank_accounts LIMIT 1").run();const proposal=createManualPostingProposal(db,{ruleId:"canonical-party",companyId:1,effectiveFrom:"2026-01-01",conditions:{company:1,documentType:"purchase_sale",currency:"DKK",vat:"positive"},outcome:{account:"5000",vatTreatment:"standard"},provenance:"test",rationale:"synthetic",creator:"user:test",createdAt:"2026-01-01T00:00:00.000Z"});expect(proposal.ok).toBe(true);if(!proposal.ok)return;expect(approvePostingRuleVersion(db,{companyId:1,ruleId:"canonical-party",version:1,actor:"user:reviewer",rationale:"synthetic",provenance:"test",expectedPayloadHash:proposal.payloadHash!,effectiveAt:"2026-01-02"}).ok).toBe(true);let result=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31"});expect(result.rows.find(row=>row.bankTransactionId===5)).toMatchObject({status:"partyUnresolved",document:{resolutionState:"unresolved",party:null}});db.query("INSERT INTO document_party_link_events(document_id,party_id,party_role,event_type,evidence_kind,evidence_json,document_sha256,document_payload_sha256,party_snapshot_json,plan_hash,actor,principal,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(3,"party-synthetic","supplier","linked","exact_identifier","{}","a".repeat(64),"b".repeat(64),'{"name":"Canonical Supplier"}',"c".repeat(64),"user:test","user:test","2026-01-05T00:00:00.000Z");result=buildBookkeepingWorkbench(db,{from:"2026-01-01",to:"2026-01-31",partyId:"party-synthetic",account:"5000",vatTreatment:"standard"});const row=result.rows.find(candidate=>candidate.bankTransactionId===5);expect(row).toMatchObject({document:{party:{id:"party-synthetic",name:"Canonical Supplier"},resolutionState:"resolved"},proposed:{account:"5000",vatTreatment:"standard"}});expect(row?.document.party?.name).not.toBe("Untrusted sender text");expect(result.population.blockers).toBeGreaterThan(0);db.close();});
});
