import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createCompany } from "../../src/core/company";
import { applyBalanceElimination, approveBalanceElimination, proposeBalanceElimination } from "../../src/core/consolidation-eliminations";
import { approveConsolidationProfile, buildConsolidatedReport, listAvailableConsolidationProfiles, parseConsolidationProfile, proposeConsolidationProfile } from "../../src/core/consolidated-reports";
import { openDb } from "../../src/core/db";
import { applyGroupManifest, readCurrentGroupManifest } from "../../src/core/group-manifest";
import { approveIntercompanyMapping, proposeIntercompanyMapping } from "../../src/core/intercompany-reconciliation";
import { postJournalEntry } from "../../src/core/ledger";
import { companyPaths } from "../../src/core/paths";
import { companyRootForSlug, initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";

function setup(ownership = 10000) {
  const workspace = mkdtempSync(join(tmpdir(), "rentemester-consolidated-report-")); initWorkspace(workspace);
  const parent=createCompany(workspace,{name:"Synthetic Parent",onboardingActor:"agent:test"}).slug, child=createCompany(workspace,{name:"Synthetic Child",onboardingActor:"agent:test"}).slug;
  const control=openWorkspaceControlDb(workspace); applyGroupManifest(control,workspace,{version:1,groups:[{id:"synthetic-group",name:"Synthetic group",memberships:[{id:"parent-member",companySlug:parent,validFrom:"2026-01-01"},{id:"child-member",companySlug:child,validFrom:"2026-01-01"}],ownership:[{id:"parent-child",parentCompanySlug:parent,childCompanySlug:child,basisPoints:ownership,evidenceRefs:["ownership-evidence"],validFrom:"2026-01-01"}]}]},{createdBy:"agent:structure",createdByProgram:"unit-test"});
  const profile={version:1,id:"synthetic-profile",groupId:"synthetic-group",currency:"DKK",validFrom:"2026-01-01",evidenceRefs:["reporting-policy"],reportingLines:[
    {id:"assets",label:"Assets",section:"asset",displayOrder:10},{id:"liabilities",label:"Liabilities",section:"liability",displayOrder:20},{id:"equity",label:"Equity",section:"equity",displayOrder:25},{id:"current-result",label:"Current result",section:"equity",role:"current-result",displayOrder:30},{id:"income",label:"Income",section:"income",displayOrder:40},{id:"expenses",label:"Expenses",section:"expense",displayOrder:50},
  ],accountMappings:[
    {id:"parent-receivable",companySlug:parent,accountNo:"1100",reportingLineId:"assets",validFrom:"2026-01-01"},{id:"parent-income",companySlug:parent,accountNo:"1000",reportingLineId:"income",validFrom:"2026-01-01"},{id:"child-payable",companySlug:child,accountNo:"7000",reportingLineId:"liabilities",validFrom:"2026-01-01"},{id:"child-equity",companySlug:child,accountNo:"5010",reportingLineId:"equity",validFrom:"2026-01-01"},
  ]};
  return{workspace,parent,child,control,profile};
}
function post(workspace:string,slug:string,lines:Array<{accountNo:string;debitAmount?:number;creditAmount?:number}>){const root=companyRootForSlug(workspace,slug),paths=companyPaths(root),db=openDb(paths.db);try{let documentId:number|undefined;if(lines.some(line=>line.accountNo==="1000"||line.accountNo==="3000")){const bytes=Buffer.from(`synthetic evidence for ${slug}: ${JSON.stringify(lines)}`),hash=createHash("sha256").update(bytes).digest("hex"),filename=`${slug}-${hash.slice(0,12)}-evidence.txt`;writeFileSync(join(paths.documentsOriginals,filename),bytes);documentId=(db.query("INSERT INTO documents (source,original_filename,stored_path,mime_type,sha256_hash,status,document_type) VALUES ('unit-test',?,?,?,?,?,'purchase_sale') RETURNING id").get(filename,`documents/originals/${filename}`,"text/plain",hash,"ingested") as {id:number}).id;}expect(postJournalEntry(db,{transactionDate:"2026-02-01",text:"Synthetic group trade",documentId,createdBy:"agent:test",createdByProgram:"unit-test",lines}).ok).toBe(true);}finally{db.close();}}
function approveProfile(control:ReturnType<typeof openWorkspaceControlDb>,workspace:string,profile:unknown){const proposed=proposeConsolidationProfile(control,workspace,profile,{createdBy:"agent:profile-proposer",createdByProgram:"unit-test"});expect(()=>approveConsolidationProfile(control,workspace,proposed.profileId,proposed.profileHash,{createdBy:"agent:profile-proposer",createdByProgram:"unit-test"})).toThrow("distinct reviewer");approveConsolidationProfile(control,workspace,proposed.profileId,proposed.profileHash,{createdBy:"agent:profile-reviewer",createdByProgram:"unit-test"});}

describe("reviewed read-only consolidated reports",()=>{
  test("maps every source account, applies a source-bound balance elimination and reconciles raw to consolidated figures",()=>{const{workspace,parent,child,control,profile}=setup();try{
    post(workspace,parent,[{accountNo:"1100",debitAmount:100},{accountNo:"1000",creditAmount:100}]); post(workspace,child,[{accountNo:"5010",debitAmount:100},{accountNo:"7000",creditAmount:100}]);
    const mapping=proposeIntercompanyMapping(control,workspace,{id:"reciprocal",groupId:"synthetic-group",leftCompanySlug:parent,rightCompanySlug:child,leftAccountNos:["1100"],rightAccountNos:["7000"],leftPosition:"receivable",rightPosition:"payable",evidenceRefs:["contract"],validFrom:"2026-01-01"},{createdBy:"agent:mapping-proposer",createdByProgram:"unit-test"}); approveIntercompanyMapping(control,workspace,mapping.mappingId,mapping.mappingHash,{createdBy:"agent:mapping-reviewer",createdByProgram:"unit-test"});
    const elimination=proposeBalanceElimination(control,workspace,{id:"balance-elimination",mappingId:"reciprocal",asOf:"2026-12-31",evidenceRefs:["review-pack"]},{createdBy:"agent:elim-proposer",createdByProgram:"unit-test"}); approveBalanceElimination(control,workspace,elimination.eliminationId,elimination.payloadHash,{createdBy:"agent:elim-reviewer",createdByProgram:"unit-test"}); applyBalanceElimination(control,workspace,elimination.eliminationId,elimination.payloadHash,{createdBy:"agent:elim-reviewer",createdByProgram:"unit-test"}); approveProfile(control,workspace,profile);
    const report=buildConsolidatedReport(control,workspace,new Set([parent,child]),"synthetic-profile","2026-01-01","2026-12-31"); expect(report.status).toBe("ready"); expect(report.blockers).toEqual([]); expect(report.appliedEliminations).toHaveLength(1); expect(report.consolidatedFigures).toEqual(expect.arrayContaining([expect.objectContaining({lineId:"assets",rawCompanySum:100,eliminationAdjustment:-100,consolidatedAmount:0}),expect.objectContaining({lineId:"liabilities",rawCompanySum:100,eliminationAdjustment:-100,consolidatedAmount:0}),expect.objectContaining({lineId:"equity",consolidatedAmount:-100}),expect.objectContaining({lineId:"income",consolidatedAmount:100}),expect.objectContaining({lineId:"expenses",consolidatedAmount:0}),expect.objectContaining({lineId:"current-result",consolidatedAmount:100})])); expect(report.sourceSnapshots).toHaveLength(2);
    expect(listAvailableConsolidationProfiles(control,workspace,new Set([parent,child]),"2026-12-31").profiles).toEqual([{id:"synthetic-profile",groupId:"synthetic-group",currency:"DKK",validFrom:"2026-01-01",validToExclusive:undefined}]);
    expect(listAvailableConsolidationProfiles(control,workspace,new Set([parent]),"2026-12-31").profiles).toEqual([]);
    post(workspace,parent,[{accountNo:"1100",debitAmount:10},{accountNo:"1000",creditAmount:10}]);
    const stale=buildConsolidatedReport(control,workspace,new Set([parent,child]),"synthetic-profile","2026-01-01","2026-12-31"); expect(stale.status).toBe("blocked"); expect(stale.consolidatedFigures).toBeNull(); expect(stale.blockers).toContain("applied elimination source snapshot changed; create and apply a new elimination");
  }finally{control.close();rmSync(workspace,{recursive:true,force:true});}});

  test("fails closed for partial visibility, non-controlling ownership and unmapped non-zero accounts",()=>{const first=setup();try{post(first.workspace,first.parent,[{accountNo:"1100",debitAmount:10},{accountNo:"5000",creditAmount:10}]);approveProfile(first.control,first.workspace,first.profile);const partial=buildConsolidatedReport(first.control,first.workspace,new Set([first.parent]),"synthetic-profile","2026-01-01","2026-12-31");expect(partial).toMatchObject({status:"blocked",consolidatedFigures:null,rawCompanySums:[],appliedEliminations:[],sourceSnapshots:[]});expect(partial.blockers).toContain("all active group companies must be visible");expect(partial.profileId).toBeUndefined();expect(partial.groupId).toBeUndefined();expect(partial.currency).toBeUndefined();const full=buildConsolidatedReport(first.control,first.workspace,new Set([first.parent,first.child]),"synthetic-profile","2026-01-01","2026-12-31");expect(full.status).toBe("blocked");expect(full.blockers).toContain("one or more non-zero company accounts lack an active reporting mapping");}finally{first.control.close();rmSync(first.workspace,{recursive:true,force:true});}
    const minority=setup(7500);try{approveProfile(minority.control,minority.workspace,minority.profile);const report=buildConsolidatedReport(minority.control,minority.workspace,new Set([minority.parent,minority.child]),"synthetic-profile","2026-01-01","2026-12-31");expect(report.status).toBe("blocked");expect(report.blockers.join(" ")).toContain("100 percent ownership");}finally{minority.control.close();rmSync(minority.workspace,{recursive:true,force:true});}}
  );

  test("rejects profiles without a current-result line and overlapping account mappings",()=>{const{workspace,control,profile}=setup();try{const groups=readCurrentGroupManifest(control,workspace)!.manifest;const noResult={...profile,reportingLines:profile.reportingLines.map((line:any)=>line.id==="current-result"?{...line,role:undefined}:line)};expect(()=>parseConsolidationProfile(noResult,groups)).toThrow("exactly one current-result");const overlap={...profile,accountMappings:[...profile.accountMappings,{...profile.accountMappings[0],id:"duplicate"}]};expect(()=>parseConsolidationProfile(overlap,groups)).toThrow("only one active");}finally{control.close();rmSync(workspace,{recursive:true,force:true});}});
});
