import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { enrichCorporateRecord, ingestCorporateRecord, linkCorporateRecord, listCorporateRecords, readCorporateRecordBytes, supersedeCorporateRecord } from "../../src/core/corporate-records";
const roots:string[]=[]; const open=()=>{const root=mkdtempSync(join(tmpdir(),"rm-record-"));roots.push(root);initWorkspace(root);return openWorkspaceControlDb(root);}; afterEach(()=>roots.splice(0).forEach(root=>{rmSync(root,{recursive:true,force:true});}));
describe("#575 immutable corporate records",()=>{
 test("keeps original bytes immutable and fails closed for a partially visible multi-company record",()=>{const db=open();const record=ingestCorporateRecord(db,{type:"board_resolution",bytes:new TextEncoder().encode("signed synthetic resolution"),filename:"resolution.pdf",source:"synthetic",receivedAt:"2026-01-01T00:00:00Z",uploader:"user:maker",actor:"user:maker",links:[{type:"company",id:"alpha"},{type:"company",id:"beta"}]});expect(new TextDecoder().decode(readCorporateRecordBytes(db,record.recordId))).toBe("signed synthetic resolution");expect(()=>ingestCorporateRecord(db,{recordId:record.recordId,type:"board_resolution",bytes:new TextEncoder().encode("changed"),filename:"resolution.pdf",source:"synthetic",receivedAt:"2026-01-01T00:00:00Z",uploader:"user:maker",actor:"user:maker"})).toThrow("immutable");expect(listCorporateRecords(db,{companySlugs:new Set(["alpha"])}).rows).toEqual([]);expect(listCorporateRecords(db,{companySlugs:new Set(["alpha","beta"])}).rows).toHaveLength(1);db.close();});
 test("allows append-only enrichment, legacy links and supersession without ledger side effects",()=>{const db=open();const one=ingestCorporateRecord(db,{type:"registration",bytes:new Uint8Array([1,2,3]),filename:"a.bin",source:"synthetic",receivedAt:"2026-01-01T00:00:00Z",uploader:"user:maker",actor:"user:maker"});const two=ingestCorporateRecord(db,{type:"registration",bytes:new Uint8Array([4,5,6]),filename:"b.bin",source:"synthetic",receivedAt:"2026-01-02T00:00:00Z",uploader:"user:maker",actor:"user:maker"});linkCorporateRecord(db,{recordId:one.recordId,type:"legacy_evidence_ref",id:"opaque-ref",actor:"user:maker"});enrichCorporateRecord(db,{recordId:one.recordId,assertion:"human checked",actor:"user:reviewer"});supersedeCorporateRecord(db,{recordId:one.recordId,replacementRecordId:two.recordId,reason:"new filing",actor:"user:reviewer"});expect(db.query("SELECT count(*) AS n FROM rm_corporate_record_events").get()).toEqual({n:5});expect(db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='journal_entries'").get()).toBeNull();db.close();});
});
