import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { createParty, linkLegacyPartyReference, linkPartyRole } from "../../src/core/party-registry";
import { migrate, openDb } from "../../src/core/db";
import { companyPaths } from "../../src/core/paths";
import { applyDocumentPartyLink, planDocumentPartyLink, supersedeDocumentPartyLink } from "../../src/core/document-party-links";
const roots:string[]=[]; const setup=()=>{const root=mkdtempSync(join(tmpdir(),"rm-doc-party-"));roots.push(root);initWorkspace(root);const registry=openWorkspaceControlDb(root);const ledger=openDb(companyPaths(root).db);migrate(ledger);ledger.query("INSERT INTO documents(document_no,sha256_hash,payload_json,upload_datetime,source,status,supplier_country_code,supplier_identifier_kind,sender_vat_cvr) VALUES(?,?,?,?,?,?,?,?,?)").run("DOC-1","a".repeat(64),"{}","2026-01-01T00:00:00.000Z","test","posted","DK","dk_cvr","DK12345678");return {root,registry,ledger};}; afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
describe("#588 document party links",()=>{
 test("fails closed for name-only, scope mismatch and unreviewed legacy evidence",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor"})).toEqual({ok:false,errors:["NO_IDENTIFIER_EVIDENCE"]});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"})).toEqual({ok:false,errors:["SCOPE_MISMATCH"]});linkLegacyPartyReference(registry,{partyId:p.partyId,companySlug:"alpha",legacyKind:"vendor",legacyId:"old",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",legacyKind:"vendor",legacyId:"old"})).toEqual({ok:false,errors:["LEGACY_REFERENCE_UNREVIEWED"]}); registry.close();ledger.close();});
 test("binds immutable evidence, applies idempotently and supersedes append-only",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:p.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});const input={documentId:1,companySlug:"alpha",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const plan=planDocumentPartyLink(ledger,registry,input);expect(plan.ok).toBeTrue();if(!plan.ok)return;expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:"bad",confirm:true,actor:"user:test",principal:"user:test"})).toEqual({ok:false,errors:["PLAN_HASH_MISMATCH"]});const applied=applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"});expect(applied).toMatchObject({ok:true,idempotent:false});expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true,idempotent:true});expect(()=>ledger.run("UPDATE document_party_link_events SET actor='x'")).toThrow("append-only");expect(supersedeDocumentPartyLink(ledger,{documentId:1,role:"vendor",planHash:plan.plan.planHash,reason:"corrected evidence",confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true});expect(ledger.query("SELECT count(*) n FROM current_document_party_links").get()).toEqual({n:0});registry.close();ledger.close();});
});
