import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { initWorkspace } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { createParty, linkLegacyPartyReference, linkPartyRole } from "../../src/core/party-registry";
import { migrate, openDb } from "../../src/core/db";
import { companyPaths } from "../../src/core/paths";
import { applyDocumentPartyLink, decideInternalNoExternalParty, documentResolution, planDocumentPartyLink, supersedeDocumentPartyLink, supersedeInternalNoExternalParty } from "../../src/core/document-party-links";
const roots:string[]=[]; const setup=()=>{const root=mkdtempSync(join(tmpdir(),"rm-doc-party-"));roots.push(root);initWorkspace(root);const registry=openWorkspaceControlDb(root);const ledger=openDb(companyPaths(root).db);migrate(ledger);ledger.query("INSERT INTO documents(document_no,sha256_hash,payload_json,upload_datetime,source,status,supplier_country_code,supplier_identifier_kind,sender_vat_cvr) VALUES(?,?,?,?,?,?,?,?,?)").run("DOC-1","a".repeat(64),"{}","2026-01-01T00:00:00.000Z","test","posted","DK","dk_cvr","DK12345678");return {root,registry,ledger};}; afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
describe("#588 document party links",()=>{
 test("fails closed for name-only, scope mismatch and unreviewed legacy evidence",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:p.partyId,companySlug:"alpha",role:"issuer",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"issuer"})).toEqual({ok:false,errors:["NO_IDENTIFIER_EVIDENCE"]});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"})).toEqual({ok:false,errors:["SCOPE_MISMATCH"]});linkLegacyPartyReference(registry,{partyId:p.partyId,companySlug:"alpha",legacyKind:"vendor",legacyId:"old",actor:"user:test"});expect(planDocumentPartyLink(ledger,registry,{documentId:1,companySlug:"alpha",role:"vendor",legacyKind:"vendor",legacyId:"old"})).toEqual({ok:false,errors:["LEGACY_REFERENCE_UNREVIEWED"]}); registry.close();ledger.close();});
 test("binds immutable evidence, applies idempotently and supersedes append-only",()=>{const {registry,ledger}=setup();const p=createParty(registry,{kind:"organization",name:"Synthetic",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:p.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});const input={documentId:1,companySlug:"alpha",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const plan=planDocumentPartyLink(ledger,registry,input);expect(plan.ok).toBeTrue();if(!plan.ok)return;expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:"bad",confirm:true,actor:"user:test",principal:"user:test"})).toEqual({ok:false,errors:["PLAN_HASH_MISMATCH"]});const applied=applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"});expect(applied).toMatchObject({ok:true,idempotent:false});expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true,idempotent:true});expect(()=>ledger.run("UPDATE document_party_link_events SET actor='x'")).toThrow("append-only");expect(supersedeDocumentPartyLink(ledger,{documentId:1,role:"vendor",planHash:plan.plan.planHash,reason:"corrected evidence",confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true});expect(ledger.query("SELECT count(*) n FROM current_document_party_links").get()).toEqual({n:0});registry.close();ledger.close();});
 test("records a confirmed immutable internal no-external-party decision",()=>{const {registry,ledger}=setup();ledger.run("UPDATE documents SET document_type='internal_voucher' WHERE id=1");const before=ledger.query("SELECT sha256_hash,payload_json,vat_amount FROM documents WHERE id=1").get();const first=decideInternalNoExternalParty(ledger,{documentId:1,reason:"Synthetic internal transfer",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"});expect(first).toMatchObject({ok:true,idempotent:false});expect(documentResolution(ledger,1).state).toBe("internal_no_external_party");expect(decideInternalNoExternalParty(ledger,{documentId:1,reason:"Synthetic internal transfer",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"})).toMatchObject({ok:true,idempotent:true});expect(decideInternalNoExternalParty(ledger,{documentId:1,reason:"different",confirm:true,actor:"user:test",principal:"user:test",idempotencyKey:"internal-1"})).toEqual({ok:false,errors:["IDEMPOTENCY_CONFLICT"]});expect(supersedeInternalNoExternalParty(ledger,{documentId:1,decisionHash:first.decisionHash,reason:"External evidence received",confirm:true,actor:"user:test",principal:"user:test"})).toMatchObject({ok:true});expect(documentResolution(ledger,1)).toMatchObject({state:"unresolved",reason:"NO_PARTY_DECISION"});expect(ledger.query("SELECT sha256_hash,payload_json,vat_amount FROM documents WHERE id=1").get()).toEqual(before);registry.close();ledger.close();});
 test("requires explicit supersession before changing the current resolution",()=>{const {registry,ledger}=setup();const party=createParty(registry,{kind:"organization",name:"Canonical vendor",identifiers:[{country:"DK",identifier:"DK12345678",identifierKind:"dk_cvr"}],source:"test",observedAt:"2026-01-01T00:00:00.000Z",reviewAssertion:"reviewed",actor:"user:test"});linkPartyRole(registry,{partyId:party.partyId,companySlug:"alpha",role:"vendor",actor:"user:test"});const input={documentId:1,companySlug:"alpha",role:"vendor" as const,jurisdiction:"DK",identifierKind:"dk_cvr",identifier:"DK12345678"};const plan=planDocumentPartyLink(ledger,registry,input);if(!plan.ok)throw new Error("expected plan");ledger.run("UPDATE documents SET document_type='internal_voucher' WHERE id=1");const internal=decideInternalNoExternalParty(ledger,{documentId:1,reason:"internal",confirm:true,actor:"user:test",principal:"user:test"});expect(internal.ok).toBeTrue();expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"})).toEqual({ok:false,errors:["CURRENT_STATE_CONFLICT"]});if(!internal.ok)throw new Error("expected internal decision");expect(supersedeInternalNoExternalParty(ledger,{documentId:1,decisionHash:internal.decisionHash,reason:"external evidence found",confirm:true,actor:"user:test",principal:"user:test"}).ok).toBeTrue();expect(applyDocumentPartyLink(ledger,registry,{...input,planHash:plan.plan.planHash,confirm:true,actor:"user:test",principal:"user:test"}).ok).toBeTrue();registry.close();ledger.close();});
});
