import { afterEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { initWorkspace } from "../../src/core/workspace";
import { createCompany } from "../../src/core/company";
import { companyPaths } from "../../src/core/paths";
import { companyRootForSlug } from "../../src/core/workspace";
import { openDb } from "../../src/core/db";
import { postJournalEntry } from "../../src/core/ledger";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { createParty } from "../../src/core/party-registry";
import { ingestCorporateRecord } from "../../src/core/corporate-records";
import { approveIntercompanyDisposition, inspectIntercompanyDisposition, intercompanyDispositionStatus, linkIntercompanyDispositionJournal, planIntercompanyDisposition, proposeIntercompanyDisposition } from "../../src/core/intercompany-dispositions";

const roots:string[]=[];
function setup(){const root=mkdtempSync(join(tmpdir(),"rm-disposition-"));roots.push(root);initWorkspace(root);const db=openWorkspaceControlDb(root);const party=createParty(db,{partyId:"party-synthetic",kind:"organization",name:"Synthetic group",source:"synthetic",observedAt:"2026-01-01T00:00:00Z",reviewAssertion:"reviewed",actor:"user:maker"});const record=ingestCorporateRecord(db,{recordId:"record-synthetic",type:"intercompany_agreement",bytes:new TextEncoder().encode("synthetic evidence"),filename:"agreement.txt",source:"synthetic",receivedAt:"2026-01-01T00:00:00Z",uploader:"synthetic",actor:"user:maker"});return {db,party,record};}
afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
const payload=(partyId:string,recordId:string)=>({dispositionId:"disp-synthetic",type:"loan",economicDate:"2026-02-01",amount:125.5,currency:"DKK",partyIds:[partyId],evidenceRecordIds:[recordId],left:{companySlug:"alpha",role:"lender",expectedSide:"receivable"},right:{companySlug:"beta",role:"borrower",expectedSide:"payable"}});

describe("#578 intercompany dispositions",()=>{
  test("keeps proposal and approval append-only with stable-principal separation",()=>{const {db,party,record}=setup();const proposed=proposeIntercompanyDisposition(db,payload(party.partyId,record.recordId),{actor:"agent:plan",principal:{kind:"service",id:"service-plan"}});expect(proposed.status).toBe("proposed");expect(()=>approveIntercompanyDisposition(db,"disp-synthetic",proposed.payloadHash,{actor:"user:review",principal:{kind:"service",id:"service-plan"}})).toThrow("distinct stable principal");const approved=approveIntercompanyDisposition(db,"disp-synthetic",proposed.payloadHash,{actor:"user:review",principal:{kind:"user",id:"user-review"}});expect(approved.status).toBe("approved");expect(inspectIntercompanyDisposition(db,"disp-synthetic")?.events.map((event:any)=>event.event_type)).toEqual(["proposed","approved"]);expect(()=>db.run("DELETE FROM rm_intercompany_disposition_events")).toThrow("append-only");db.close();});
  test("rejects incomplete evidence and asymmetric economic sides",()=>{const {db}=setup();expect(()=>proposeIntercompanyDisposition(db,{...payload("missing","missing"),right:{companySlug:"alpha",role:"same",expectedSide:"payable"}},{actor:"user:maker",principal:{kind:"user",id:"maker"}})).toThrow("distinct legal companies");expect(()=>proposeIntercompanyDisposition(db,payload("missing","missing"),{actor:"user:maker",principal:{kind:"user",id:"maker"}})).toThrow("party does not exist");db.close();});
  test("plans without mutation and makes one-sided/stale links visible without writing either ledger",()=>{const {db,party,record}=setup();
    db.close();const workspace=roots.at(-1)!;const left=createCompany(workspace,{name:"Left",onboardingActor:"user:maker"});const right=createCompany(workspace,{name:"Right",onboardingActor:"user:maker"});const control=openWorkspaceControlDb(workspace);const input={...payload(party.partyId,record.recordId),left:{companySlug:left.slug,role:"lender",expectedSide:"receivable" as const},right:{companySlug:right.slug,role:"borrower",expectedSide:"payable" as const}};const plan=planIntercompanyDisposition(control,input);expect(plan.ledgerEffects).toEqual([]);const proposed=proposeIntercompanyDisposition(control,input,{actor:"user:maker",principal:{kind:"user",id:"maker"}});const approved=approveIntercompanyDisposition(control,input.dispositionId,proposed.payloadHash,{actor:"user:review",principal:{kind:"user",id:"review"}});
    const post=(slug:string,lines:any[])=>{const ledger=openDb(companyPaths(companyRootForSlug(workspace,slug)).db);const before=ledger.query("SELECT count(*) count FROM journal_entries").get()as any;const result=postJournalEntry(ledger,{transactionDate:"2026-02-01",text:"Synthetic disposition",createdBy:"user:maker",createdByProgram:"test",lines});const head=ledger.query("SELECT entry_hash FROM journal_entries ORDER BY id DESC LIMIT 1").get()as any;const after=ledger.query("SELECT count(*) count FROM journal_entries").get()as any;ledger.close();expect(result.ok).toBe(true);expect(after.count).toBe(before.count+1);return {id:result.entryId!,head:head.entry_hash};};
    const leftJournal=post(left.slug,[{accountNo:"1100",debitAmount:125.5},{accountNo:"5000",creditAmount:125.5}]);const leftCount=openDb(companyPaths(companyRootForSlug(workspace,left.slug)).db);const beforeLinks=leftCount.query("SELECT count(*) count FROM journal_entries").get()as any;leftCount.close();const linked=linkIntercompanyDispositionJournal(control,workspace,{dispositionId:input.dispositionId,payloadHash:approved.payloadHash,side:"left",journalEntryId:Number(leftJournal.id),expectedLedgerHeadHash:leftJournal.head,actor:"user:link",principal:{kind:"user",id:"linker"}});expect(linked.status).toBe("partly_posted");const unchanged=openDb(companyPaths(companyRootForSlug(workspace,left.slug)).db);expect(unchanged.query("SELECT count(*) count FROM journal_entries").get()).toEqual(beforeLinks);unchanged.close();const oneSided=intercompanyDispositionStatus(control,workspace,input.dispositionId,"2026-03-01")!;expect(oneSided.exceptions.some((e:any)=>e.kind==="one_sided_posting")).toBe(true);
    // A later ordinary posting changes the ledger head, so linking the other side fails closed.
    post(left.slug,[{accountNo:"1100",debitAmount:1},{accountNo:"5000",creditAmount:1}]);const rightJournal=post(right.slug,[{accountNo:"5000",debitAmount:125.5},{accountNo:"7000",creditAmount:125.5}]);expect(()=>linkIntercompanyDispositionJournal(control,workspace,{dispositionId:input.dispositionId,payloadHash:approved.payloadHash,side:"right",journalEntryId:Number(rightJournal.id),expectedLedgerHeadHash:rightJournal.head,actor:"user:link",principal:{kind:"user",id:"linker"}})).toThrow("linked ledger head changed");control.close();});
});
