import { describe, expect, test } from "bun:test";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openDb, migrate } from "../../src/core/db";
import { applySupplierCommitment, changeSupplierCommitment, matchSupplierCommitmentOccurrence, planSupplierCommitment, plannedCommitmentOccurrences, supplierCommitmentAlerts } from "../../src/core/supplier-commitments";
import { buildThirteenWeekLiquidityForecast } from "../../src/core/liquidity-forecast";
const fixture=()=>{const db=openDb(join(mkdtempSync(join(tmpdir(),"rm-commitment-")),"ledger.sqlite"));migrate(db);return db;};
const base={commitmentId:"commitment-synthetic",vendorPartyId:"party-supplier",type:"subscription",description:"Synthetic service",businessPurpose:"Synthetic test",amount:100,currency:"DKK",frequency:"monthly" as const,nextDate:"2026-01-31",evidenceRefs:["record-synthetic"]};
describe("supplier commitments",()=>{
 test("plans recurrence deterministically without a ledger effect",()=>{const p=planSupplierCommitment(base);expect(p.ok).toBe(true);if(p.ok){expect(p.proposal.schedule.map(x=>x.date).slice(0,3)).toEqual(["2026-01-31","2026-02-28","2026-03-28"]);expect(p.proposal.warnings[0]).toContain("VAT");}});
 test("requires exact hash, confirm, actor and idempotency",()=>{const db=fixture();try{const p=planSupplierCommitment(base);if(!p.ok)throw Error();expect(applySupplierCommitment(db,{...base,payloadHash:p.proposal.payloadHash,confirm:false})).toMatchObject({ok:false});const first=applySupplierCommitment(db,{...base,payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test",idempotencyKey:"one"});expect(first).toMatchObject({ok:true,idempotent:false});expect(applySupplierCommitment(db,{...base,payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test",idempotencyKey:"one"})).toMatchObject({ok:true,idempotent:true});expect(applySupplierCommitment(db,{...base,amount:101,payloadHash:planSupplierCommitment({...base,amount:101}).proposal!.payloadHash,confirm:true,actor:"agent:test",principal:"service:test",idempotencyKey:"one"})).toMatchObject({ok:false,errors:["IDEMPOTENCY_CONFLICT"]});}finally{db.close();}});
 test("pause preserves historical event and stops future cash inclusion",()=>{const db=fixture();try{const p=planSupplierCommitment({...base,nextDate:"2026-01-05",frequency:"weekly"});if(!p.ok)throw Error();applySupplierCommitment(db,{...base,nextDate:"2026-01-05",frequency:"weekly",payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test"});expect(plannedCommitmentOccurrences(db,"2026-01-01",2)).toHaveLength(2);expect(changeSupplierCommitment(db,{commitmentId:base.commitmentId,action:"paused",reason:"review",confirm:true,actor:"agent:test",principal:"service:test"})).toMatchObject({ok:true});expect(plannedCommitmentOccurrences(db,"2026-01-01",2)).toHaveLength(0);}finally{db.close();}});
 test("generates the rolling schedule beyond the approval preview horizon",()=>{const db=fixture();try{const p=planSupplierCommitment(base);if(!p.ok)throw Error();applySupplierCommitment(db,{...base,payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test"});expect(plannedCommitmentOccurrences(db,"2027-01-01",5).map(row=>row.date)).toEqual(["2027-01-28"]);}finally{db.close();}});
 test("13 week forecast keeps foreign currency excluded and labels sources",()=>{const db=fixture();try{const p=planSupplierCommitment({...base,currency:"EUR",nextDate:"2026-01-05"});if(!p.ok)throw Error();applySupplierCommitment(db,{...base,currency:"EUR",nextDate:"2026-01-05",payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test"});const forecast=buildThirteenWeekLiquidityForecast(db,{startDate:"2026-01-01"});expect(forecast.ok).toBe(true);expect(forecast.periods[0]!.excluded).toEqual([{source:base.commitmentId,amount:100,currency:"EUR"}]);expect(forecast.completeness.excluded.join(" ")).toContain("dated FX");}finally{db.close();}});
 test("confirmed match resolves canonical evidence, rejects fake caller fields and makes FX explicit",()=>{const db=fixture();try{const p=planSupplierCommitment({...base,nextDate:"2026-01-31",renewalDate:"2026-02-10",noticeDate:"2026-01-15"});if(!p.ok)throw Error();applySupplierCommitment(db,{...base,nextDate:"2026-01-31",renewalDate:"2026-02-10",noticeDate:"2026-01-15",payloadHash:p.proposal.payloadHash,confirm:true,actor:"agent:test",principal:"service:test"});db.query("INSERT INTO documents(document_no,source,sha256_hash,invoice_date,amount_inc_vat,currency) VALUES(?,?,?,?,?,?)").run("D-1","synthetic","a".repeat(64),"2026-02-01",110,"EUR");const input={commitmentId:base.commitmentId,occurrenceDate:"2026-01-31",evidence:{kind:"canonical_document" as const,id:"1"},confirm:true,actor:"agent:test",principal:"service:test"};const matched=matchSupplierCommitmentOccurrence(db,input);expect(matched).toMatchObject({ok:true,variance:{amount:null,dateDays:1,currency:{status:"unsupported_fx"},documentation:"present",party:{expected:"party-supplier",actual:null,status:"missing"}}});expect(plannedCommitmentOccurrences(db,"2026-01-31",1)).toEqual([]);expect(matchSupplierCommitmentOccurrence(db,{...input,evidence:{kind:"canonical_document",id:"2"}})).toMatchObject({ok:false,errors:["CANONICAL_EVIDENCE_NOT_FOUND_OR_UNSUPPORTED"]});expect(supplierCommitmentAlerts(db,"2026-01-12")).toEqual([{commitmentId:base.commitmentId,kind:"notice",date:"2026-01-15",severity:"upcoming"},{commitmentId:base.commitmentId,kind:"renewal",date:"2026-02-10",severity:"upcoming"}]);}finally{db.close();}});
});
