import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { rmSync } from "node:fs";
import { openDb, migrate } from "../../src/core/db";
import { companyPaths } from "../../src/core/paths";
import { companyRootForSlug } from "../../src/core/workspace";
import { openWorkspaceControlDb } from "../../src/core/workspace-control";
import { approveWorkspaceInboxAssignment, completeWorkspaceInboxAssignment, ingestWorkspaceInboxSource, inspectWorkspaceInboxSource } from "../../src/core/workspace-document-inbox";
import { makeWorkspace } from "./server-api/_shared";

const bytes = new TextEncoder().encode("synthetic workspace inbox evidence");
const metadata = { issueDate:"2026-05-16",invoiceNo:"INBOX-1",deliveryDescription:"Synthetic service",amountIncVat:125,currency:"DKK",sender:{name:"Synthetic Supplier",address:"Example Road 1",vatOrCvr:"DK11223344"},recipient:{name:"Synthetic Buyer",address:"Example Road 2",vatOrCvr:"DK12345678"},vatAmount:25 };
function ledgerState(path:string){const db=openDb(path);try{return {documents:db.query("SELECT count(*) AS n FROM documents").get(),journals:db.query("SELECT count(*) AS n FROM journal_entries").get(),audit:db.query("SELECT count(*) AS n FROM audit_log").get()};}finally{db.close();}}
function source(db:ReturnType<typeof openWorkspaceControlDb>, key:string, candidates:any[]=[]){return ingestWorkspaceInboxSource(db,{visibilityAnchorSlug:"alpha-company",idempotencyKey:key,bytes,filename:"synthetic.txt",mimeType:"text/plain",transport:"upload",receivedAt:"2026-08-30T09:00:00Z",metadata,candidates,visibleCompanySlugs:new Set(["alpha-company","beta-company"]),actor:"agent:test"});}

describe("workspace document inbox",()=>{
  test("keeps an unmatched source in control state and out of every ledger",()=>{const ws=makeWorkspace("workspace-inbox-unmatched",["Alpha Company","Beta Company"]);try{const alpha=companyPaths(companyRootForSlug(ws,"alpha-company")).db,beta=companyPaths(companyRootForSlug(ws,"beta-company")).db,before=[ledgerState(alpha),ledgerState(beta)];const db=openWorkspaceControlDb(ws);try{const item=source(db,"inbox-unmatched");expect(item.exception?.code).toBe("INBOX_NO_CANDIDATE");expect(item.assignments).toHaveLength(0);expect(inspectWorkspaceInboxSource(db,item.sourceId,"alpha-company")?.sha256).toBe(createHash("sha256").update(bytes).digest("hex"));expect(inspectWorkspaceInboxSource(db,item.sourceId,"beta-company")).toBeNull();}finally{db.close();}expect([ledgerState(alpha),ledgerState(beta)]).toEqual(before);}finally{rmSync(ws,{recursive:true,force:true});}});
  test("filters hidden candidates before ambiguity, and exact retries do not duplicate",()=>{const ws=makeWorkspace("workspace-inbox-candidates",["Alpha Company","Beta Company"]);try{const db=openWorkspaceControlDb(ws);try{const visible=ingestWorkspaceInboxSource(db,{visibilityAnchorSlug:"alpha-company",idempotencyKey:"inbox-visible",bytes,filename:"synthetic.txt",mimeType:"text/plain",transport:"mail",transportIdentity:"message-1",receivedAt:"2026-08-30T09:00:00Z",metadata,candidates:[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"},{companySlug:"hidden-company",evidenceKind:"buyer_vat",evidence:"private"}],visibleCompanySlugs:new Set(["alpha-company"]),actor:"agent:test"});expect(visible.exception).toBeNull();expect(visible.history.find((e:any)=>e.event_type==="candidate_resolved")?.payload.candidates).toEqual([{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"}]);expect(source(db,"inbox-visible",[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"}]).sourceId).toBe(visible.sourceId);const ambiguous=source(db,"inbox-ambiguous",[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"a"},{companySlug:"beta-company",evidenceKind:"buyer_vat",evidence:"b"}]);expect(ambiguous.exception?.code).toBe("INBOX_AMBIGUOUS_CANDIDATES");}finally{db.close();}}finally{rmSync(ws,{recursive:true,force:true});}});
  test("hands off exactly once and rejects reassignment after a company document exists",()=>{const ws=makeWorkspace("workspace-inbox-handoff",["Alpha Company","Beta Company"]);try{const control=openWorkspaceControlDb(ws);const root=companyRootForSlug(ws,"alpha-company"),ledger=openDb(companyPaths(root).db);try{migrate(ledger);const item=source(control,"inbox-handoff",[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"}]);approveWorkspaceInboxAssignment(control,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test"});const completed=completeWorkspaceInboxAssignment(control,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test"});expect(completed.assignments).toMatchObject([{companySlug:"alpha-company",state:"completed",documentNo:expect.any(String)}]);expect(completeWorkspaceInboxAssignment(control,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test"}).history.filter((e:any)=>e.event_type==="handoff_completed")).toHaveLength(1);expect(()=>approveWorkspaceInboxAssignment(control,{sourceId:item.sourceId,companySlug:"beta-company",actor:"agent:test"})).toThrow("already handed off");expect(ledger.query("SELECT source,sha256_hash FROM documents WHERE source=?").get(`workspace-inbox:${item.sourceId}`)).toMatchObject({sha256_hash:createHash("sha256").update(bytes).digest("hex")});}finally{ledger.close();control.close();}}finally{rmSync(ws,{recursive:true,force:true});}});
  test("recovers an expired durable claim after a lost response without duplicate company ingest",()=>{const ws=makeWorkspace("workspace-inbox-claim",["Alpha Company"]);try{const control=openWorkspaceControlDb(ws),root=companyRootForSlug(ws,"alpha-company"),ledger=openDb(companyPaths(root).db);try{migrate(ledger);const item=source(control,"inbox-claim",[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"}]);approveWorkspaceInboxAssignment(control,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test"});expect(()=>completeWorkspaceInboxAssignment(control,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test",at:"2026-08-30T10:00:00.000Z",leaseMs:1000,faultAt:"after-company-ingest"})).toThrow("after company ingest");expect(ledger.query("SELECT count(*) AS n FROM documents WHERE source=?").get(`workspace-inbox:${item.sourceId}`)).toEqual({n:1});const done=completeWorkspaceInboxAssignment(control,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test",at:"2026-08-30T10:00:02.000Z"});expect(done.assignments[0]).toMatchObject({state:"completed"});expect(ledger.query("SELECT count(*) AS n FROM documents WHERE source=?").get(`workspace-inbox:${item.sourceId}`)).toEqual({n:1});expect(done.history.filter((e:any)=>e.event_type==="handoff_completed")).toHaveLength(1);}finally{ledger.close();control.close();}}finally{rmSync(ws,{recursive:true,force:true});}});
  test("an independent control connection cannot steal a live handoff claim",()=>{const ws=makeWorkspace("workspace-inbox-live-claim",["Alpha Company"]);try{const first=openWorkspaceControlDb(ws),second=openWorkspaceControlDb(ws),root=companyRootForSlug(ws,"alpha-company"),ledger=openDb(companyPaths(root).db);try{migrate(ledger);const item=source(first,"inbox-live",[{companySlug:"alpha-company",evidenceKind:"buyer_vat",evidence:"verified"}]);approveWorkspaceInboxAssignment(first,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test"});expect(()=>completeWorkspaceInboxAssignment(first,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:test",at:"2026-08-30T10:00:00.000Z",leaseMs:60000,faultAt:"before-company-ingest"})).toThrow("before company ingest");expect(()=>completeWorkspaceInboxAssignment(second,ledger,root,{sourceId:item.sourceId,companySlug:"alpha-company",actor:"agent:other",at:"2026-08-30T10:00:01.000Z"})).toThrow("already in progress");expect(ledger.query("SELECT count(*) AS n FROM documents").get()).toEqual({n:0});}finally{ledger.close();second.close();first.close();}}finally{rmSync(ws,{recursive:true,force:true});}});
});
